const API_BASE = import.meta.env.VITE_API_BASE_URL ?? ''
let csrfToken = null
let csrfHeaderName = 'X-CSRF-Token'

async function request(path, options = {}) {
  const headers = { ...(options.headers ?? {}) }
  if (options.body && !(options.body instanceof FormData)) headers['Content-Type'] = 'application/json'
  if (options.method && options.method !== 'GET') {
    if (!csrfToken) await getCsrf()
    headers[csrfHeaderName] = csrfToken
  }
  const response = await fetch(`${API_BASE}${path}`, { credentials: 'include', ...options, headers })
  if (!response.ok) {
    let message = response.status === 401 ? 'Your admin session has expired.' : 'Request failed.'
    try { const data = await response.json(); message = data.error?.message ?? data.detail ?? message } catch { /* safe generic message */ }
    const error = new Error(typeof message === 'string' ? message : 'Validation failed.')
    error.status = response.status
    throw error
  }
  return response.json()
}

export async function login(username, password) {
  const data = await fetch(`${API_BASE}/api/admin/auth/login`, {
    method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ username, password }),
  })
  if (!data.ok) throw new Error('Invalid username or password.')
  csrfToken = null
  await getCsrf()
  return data.json()
}

export const getMe = () => request('/api/admin/auth/me')
export async function getCsrf() {
  const data = await fetch(`${API_BASE}/api/admin/auth/csrf`, { credentials: 'include' })
  if (!data.ok) throw new Error('Authentication required.')
  const payload = await data.json()
  csrfToken = payload.csrf_token
  csrfHeaderName = payload.header_name
  return csrfToken
}
export async function logout() { const result = await request('/api/admin/auth/logout', { method: 'POST' }); csrfToken = null; return result }
export const getOverview = () => request('/api/admin/overview')
export async function getSystemStatus() {
  const [database, configuration, schema, audit] = await Promise.all([
    request('/api/admin/system/database'), request('/api/admin/system/configuration'),
    request('/api/admin/system/schema'), request('/api/admin/audit/recent?limit=8'),
  ])
  return { database, configuration, schema, audit }
}
export const datasetStatistics = () => request('/api/admin/datasets/statistics')
export const datasetSources = (query = '') => request(`/api/admin/datasets/sources${query}`)
export const createDatasetSource = (body) => request('/api/admin/datasets/sources', { method: 'POST', body: JSON.stringify(body) })
export const updateDatasetSource = (id, body) => request(`/api/admin/datasets/sources/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const datasetRecords = (query = '') => request(`/api/admin/datasets/records${query}`)
export const createDatasetRecord = (body) => request('/api/admin/datasets/records', { method: 'POST', body: JSON.stringify(body) })
export const updateDatasetRecord = (id, body) => request(`/api/admin/datasets/records/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const datasetDuplicates = () => request('/api/admin/datasets/duplicates')
export const recordAction = (id, action, body) => request(`/api/admin/datasets/records/${id}/${action}`, { method: 'POST', body: body ? JSON.stringify(body) : undefined })
export const recordReviews = (id) => request(`/api/admin/datasets/records/${id}/reviews`)
export const importJobs = (query = '') => request(`/api/admin/datasets/imports${query}`)
export const importRows = (id, query = '') => request(`/api/admin/datasets/imports/${id}/rows${query}`)
export const importEvents = (id) => request(`/api/admin/datasets/imports/${id}/events`)
export const uploadImport = (form) => request('/api/admin/datasets/imports', { method: 'POST', body: form })
export const parseImport = (id) => request(`/api/admin/datasets/imports/${id}/parse`, { method: 'POST' })
export const updateImportMapping = (id, body) => request(`/api/admin/datasets/imports/${id}/mapping`, { method: 'PATCH', body: JSON.stringify(body) })
export const confirmImport = (id, body) => request(`/api/admin/datasets/imports/${id}/confirm`, { method: 'POST', body: JSON.stringify(body) })
export const cancelImport = (id) => request(`/api/admin/datasets/imports/${id}/cancel`, { method: 'POST' })
export async function downloadImportReport(id) {
  if (!csrfToken) await getCsrf()
  const response = await fetch(`${API_BASE}/api/admin/datasets/imports/${id}/report`, { credentials: 'include', headers: { [csrfHeaderName]: csrfToken } })
  if (!response.ok) throw new Error('Could not create the import report.')
  return response.blob()
}
export const documentCapabilities = () => request('/api/admin/documents/capabilities')
export const documents = (query = '') => request(`/api/admin/documents${query}`)
export const documentDetail = (id) => request(`/api/admin/documents/${id}`)
export const uploadDocument = (form) => request('/api/admin/documents', { method: 'POST', body: form })
export const analyzeDocument = (id) => request(`/api/admin/documents/${id}/analyze`, { method: 'POST' })
export const processDocument = (id, body) => request(`/api/admin/documents/${id}/process`, { method: 'POST', body: JSON.stringify(body) })
export const documentPages = (id, query = '') => request(`/api/admin/documents/${id}/pages${query}`)
export const documentPage = (id, number) => request(`/api/admin/documents/${id}/pages/${number}`)
export const editDocumentPage = (id, number, body) => request(`/api/admin/documents/${id}/pages/${number}`, { method: 'PATCH', body: JSON.stringify(body) })
export const reprocessDocumentPage = (id, number, body) => request(`/api/admin/documents/${id}/pages/${number}/reprocess`, { method: 'POST', body: JSON.stringify(body) })
export const segmentDocument = (id, body) => request(`/api/admin/documents/${id}/segment`, { method: 'POST', body: JSON.stringify(body) })
export const documentCandidates = (id, query = '') => request(`/api/admin/documents/${id}/candidates${query}`)
export const editDocumentCandidate = (id, candidate, body) => request(`/api/admin/documents/${id}/candidates/${candidate}`, { method: 'PATCH', body: JSON.stringify(body) })
export const documentCandidateAction = (id, candidate, action) => request(`/api/admin/documents/${id}/candidates/${candidate}/${action}`, { method: 'POST' })
export const importDocumentCandidates = (id) => request(`/api/admin/documents/${id}/candidates/import`, { method: 'POST', body: JSON.stringify({ confirm: true }) })
export const documentJobs = (id) => request(`/api/admin/documents/${id}/jobs`)
export const documentJobEvents = (id) => request(`/api/admin/documents/jobs/${id}/events`)
export async function downloadDocumentReport(id) {
  const response = await fetch(`${API_BASE}/api/admin/documents/${id}/report`, { credentials: 'include' })
  if (!response.ok) throw new Error('Could not create the document report.')
  return response.blob()
}
export const qualitySummary = () => request('/api/admin/datasets/quality/summary')
export const qualityIssues = (query = '') => request(`/api/admin/datasets/quality/issues${query}`)
export const assessQuality = (body = {}) => request('/api/admin/datasets/quality/assess', { method: 'POST', body: JSON.stringify(body) })
export const assessRecordQuality = (id) => request(`/api/admin/datasets/records/${id}/quality/assess`, { method: 'POST', body: JSON.stringify({ force: true }) })
export const recordQuality = (id) => request(`/api/admin/datasets/records/${id}/quality`)
export const datasetVersions = (query = '') => request(`/api/admin/datasets/versions${query}`)
export const createDatasetVersion = (body) => request('/api/admin/datasets/versions', { method: 'POST', body: JSON.stringify(body) })
export const datasetVersion = (id) => request(`/api/admin/datasets/versions/${id}`)
export const datasetVersionItems = (id, query = '') => request(`/api/admin/datasets/versions/${id}/items${query}`)
export const datasetVersionManifest = (id) => request(`/api/admin/datasets/versions/${id}/manifest`)
export const verifyDatasetVersion = (id) => request(`/api/admin/datasets/versions/${id}/verify`, { method: 'POST' })
export const createDatasetBuild = (body) => request('/api/admin/datasets/builds', { method: 'POST', body: JSON.stringify(body) })
export const datasetBuilds = (query = '') => request(`/api/admin/datasets/builds${query}`)
export const validateDatasetBuild = (id) => request(`/api/admin/datasets/builds/${id}/validate`, { method: 'POST' })
export const runDatasetBuild = (id, body) => request(`/api/admin/datasets/builds/${id}/run`, { method: 'POST', body: JSON.stringify(body) })
export const datasetBuildEvents = (id) => request(`/api/admin/datasets/builds/${id}/events`)
export const createDatasetExport = (id, body = { export_format: 'jsonl' }) => request(`/api/admin/datasets/versions/${id}/exports`, { method: 'POST', body: JSON.stringify(body) })
export const datasetExports = (id) => request(`/api/admin/datasets/versions/${id}/exports`)
export const verifyDatasetExport = (id) => request(`/api/admin/datasets/exports/${id}/verify`, { method: 'POST' })
export const tokenizerCapabilities = () => request('/api/admin/tokenizers/capabilities')
export const tokenizerFamilies = (query = '') => request(`/api/admin/tokenizers/families${query}`)
export const createTokenizerFamily = (body) => request('/api/admin/tokenizers/families', { method: 'POST', body: JSON.stringify(body) })
export const tokenizerVersions = (query = '') => request(`/api/admin/tokenizers/versions${query}`)
export const createTokenizerVersion = (body) => request('/api/admin/tokenizers/versions', { method: 'POST', body: JSON.stringify(body) })
export const tokenizerJobs = (query = '') => request(`/api/admin/tokenizers/jobs${query}`)
export const createTokenizerJob = (body) => request('/api/admin/tokenizers/jobs', { method: 'POST', body: JSON.stringify(body) })
export const tokenizerJobAction = (id, action) => request(`/api/admin/tokenizers/jobs/${id}/${action}`, { method: 'POST' })
export const tokenizerJobEvents = (id) => request(`/api/admin/tokenizers/jobs/${id}/events`)
export const tokenizerEncode = (id, text) => request(`/api/admin/tokenizers/versions/${id}/encode`, { method: 'POST', body: JSON.stringify({ text }) })
export const tokenizerDecode = (id, ids) => request(`/api/admin/tokenizers/versions/${id}/decode`, { method: 'POST', body: JSON.stringify({ ids }) })
export const tokenizerCompare = (body) => request('/api/admin/tokenizers/compare', { method: 'POST', body: JSON.stringify(body) })
export const activateTokenizer = (id) => request(`/api/admin/tokenizers/versions/${id}/activate`, { method: 'POST' })
export const retireTokenizer = (id) => request(`/api/admin/tokenizers/versions/${id}/retire`, { method: 'POST' })
export const verifyTokenizer = (id) => request(`/api/admin/tokenizers/versions/${id}/verify`, { method: 'POST' })
export const tokenizerAssignments = () => request('/api/admin/tokenizers/assignments')
export const patchTokenizerAssignment = (key, body) => request(`/api/admin/tokenizers/assignments/${key}`, { method: 'PATCH', body: JSON.stringify(body) })
export const createTokenizerExport = (id, body = { export_format: 'sentencepiece_bundle' }) => request(`/api/admin/tokenizers/versions/${id}/exports`, { method: 'POST', body: JSON.stringify(body) })
export const tokenizerExports = (id) => request(`/api/admin/tokenizers/versions/${id}/exports`)
export const verifyTokenizerExport = (id) => request(`/api/admin/tokenizers/exports/${id}/verify`, { method: 'POST' })
export const coreModelCapabilities = () => request('/api/admin/core-models/capabilities')
export const coreModelFamilies = (query = '') => request(`/api/admin/core-models/families${query}`)
export const createCoreModelFamily = (body) => request('/api/admin/core-models/families', { method: 'POST', body: JSON.stringify(body) })
export const coreModelConfigs = (query = '') => request(`/api/admin/core-models/configs${query}`)
export const estimateCoreModelConfig = (body) => request('/api/admin/core-models/configs/estimate', { method: 'POST', body: JSON.stringify(body) })
export const createCoreModelConfig = (body) => request('/api/admin/core-models/configs', { method: 'POST', body: JSON.stringify(body) })
export const validateCoreModelConfig = (id) => request(`/api/admin/core-models/configs/${id}/validate`, { method: 'POST' })
export const coreModelVersions = (query = '') => request(`/api/admin/core-models/versions${query}`)
export const createCoreModelVersion = (body) => request('/api/admin/core-models/versions', { method: 'POST', body: JSON.stringify(body) })
export const coreModelVersionAction = (id, action, body) => request(`/api/admin/core-models/versions/${id}/${action}`, { method: 'POST', body: body ? JSON.stringify(body) : undefined })
export const coreModelChecks = (id) => request(`/api/admin/core-models/versions/${id}/checks`)
export const coreModelCheckpoints = (id) => request(`/api/admin/core-models/versions/${id}/checkpoints`)
export const verifyCoreModelCheckpoint = (id) => request(`/api/admin/core-models/checkpoints/${id}/verify`, { method: 'POST' })
export const coreModelAssignments = () => request('/api/admin/core-models/assignments')
export const patchCoreModelAssignment = (key, body) => request(`/api/admin/core-models/assignments/${key}`, { method: 'PATCH', body: JSON.stringify(body) })
export const pretrainingCapabilities = () => request('/api/admin/pretraining/capabilities')
export const pretrainingEstimate = (body) => request('/api/admin/pretraining/estimate', { method: 'POST', body: JSON.stringify(body) })
export const pretrainingPreflight = (body) => request('/api/admin/pretraining/preflight', { method: 'POST', body: JSON.stringify(body) })
export const pretrainingJobs = (query = '') => request(`/api/admin/pretraining/jobs${query}`)
export const createPretrainingJob = (body) => request('/api/admin/pretraining/jobs', { method: 'POST', body: JSON.stringify(body) })
export const pretrainingJobAction = (id, action) => request(`/api/admin/pretraining/jobs/${id}/${action}`, { method: 'POST' })
export const pretrainingEvents = (id) => request(`/api/admin/pretraining/jobs/${id}/events`)
export const pretrainingMetrics = (id) => request(`/api/admin/pretraining/jobs/${id}/metrics`)
export const pretrainingCheckpoints = (id) => request(`/api/admin/pretraining/jobs/${id}/checkpoints`)
export const verifyPretrainingCheckpoint = (id) => request(`/api/admin/pretraining/checkpoints/${id}/verify`, { method: 'POST' })
export const promotePretrainingCheckpoint = (id, overrideComment) => request(`/api/admin/pretraining/checkpoints/${id}/promote`, { method: 'POST', body: JSON.stringify(overrideComment ? { override_comment: overrideComment } : {}) })
export const pretrainingWorkers = () => request('/api/admin/pretraining/workers')
export const pretrainingWorker = (id) => request(`/api/admin/pretraining/workers/${id}`)
export const generatePretrainingCoverage = (id) => request(`/api/admin/pretraining/jobs/${id}/coverage`, { method: 'POST' })
export const pretrainingCoverage = (id) => request(`/api/admin/pretraining/jobs/${id}/coverage`)
export const pretrainingStreams = (id) => request(`/api/admin/pretraining/jobs/${id}/streams`)
export const verifyPretrainingStreams = (id) => request(`/api/admin/pretraining/jobs/${id}/streams/verify`, { method: 'POST' })
export const staleJobs = () => request('/api/admin/pretraining/recovery/stale-jobs')
export const recoverPretrainingJob = (id, comment) => request(`/api/admin/pretraining/jobs/${id}/recover`, { method: 'POST', body: JSON.stringify(comment ? { comment } : {}) })
export const jobRecoveries = (id) => request(`/api/admin/pretraining/jobs/${id}/recoveries`)
export const pretrainingSummary = (id) => request(`/api/admin/pretraining/jobs/${id}/summary`)
export const assessJobQuality = (id) => request(`/api/admin/pretraining/jobs/${id}/quality/assess`, { method: 'POST' })
export const jobQuality = (id) => request(`/api/admin/pretraining/jobs/${id}/quality`)
export const jobQualityIssues = (id) => request(`/api/admin/pretraining/jobs/${id}/quality/issues`)
export const compareCheckpoints = (left, right) => request('/api/admin/pretraining/checkpoints/compare', { method: 'POST', body: JSON.stringify({ left_checkpoint_public_id: left, right_checkpoint_public_id: right }) })
export const compareJobs = (left, right) => request('/api/admin/pretraining/jobs/compare', { method: 'POST', body: JSON.stringify({ left_job_public_id: left, right_job_public_id: right }) })
export const retentionPreview = (id) => request(`/api/admin/pretraining/jobs/${id}/retention/preview`, { method: 'POST' })
export const retentionApply = (id, checkpointIds) => request(`/api/admin/pretraining/jobs/${id}/retention/apply`, { method: 'POST', body: JSON.stringify({ checkpoint_public_ids: checkpointIds }) })

export const baseTrainingExperiments = (query = '') => request(`/api/admin/base-training/experiments${query}`)
export const createBaseTrainingExperiment = (body) => request('/api/admin/base-training/experiments', { method: 'POST', body: JSON.stringify(body) })
export const baseTrainingExperiment = (id) => request(`/api/admin/base-training/experiments/${id}`)
export const patchBaseTrainingExperiment = (id, body) => request(`/api/admin/base-training/experiments/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const generateBaseTrainingProfile = (id) => request(`/api/admin/base-training/experiments/${id}/profile`, { method: 'POST' })
export const baseTrainingProfile = (id) => request(`/api/admin/base-training/experiments/${id}/profile`)
export const evaluateBaseTrainingTokenizer = (id) => request(`/api/admin/base-training/experiments/${id}/tokenizer-evaluate`, { method: 'POST' })
export const baseTrainingTokenizerEvaluation = (id) => request(`/api/admin/base-training/experiments/${id}/tokenizer-evaluation`)
export const createBaseTrainingRun = (id, body) => request(`/api/admin/base-training/experiments/${id}/runs`, { method: 'POST', body: JSON.stringify(body) })
export const baseTrainingRuns = (id) => request(`/api/admin/base-training/experiments/${id}/runs`)
export const baseTrainingRun = (runId) => request(`/api/admin/base-training/runs/${runId}`)
export const queueBaseTrainingRun = (runId) => request(`/api/admin/base-training/runs/${runId}/queue`, { method: 'POST' })
export const evaluateBaseTrainingRun = (runId) => request(`/api/admin/base-training/runs/${runId}/evaluate`, { method: 'POST' })
export const baseTrainingLanguageMetrics = (runId) => request(`/api/admin/base-training/runs/${runId}/language-metrics`)
export const baseTrainingLearningChecks = (runId) => request(`/api/admin/base-training/runs/${runId}/learning-checks`)
export const compareBaseTrainingRuns = (id, left, right) => request(`/api/admin/base-training/experiments/${id}/compare-runs`, { method: 'POST', body: JSON.stringify({ left_run_public_id: left, right_run_public_id: right }) })
export const baseTrainingComparisons = (id) => request(`/api/admin/base-training/experiments/${id}/comparisons`)
export const selectBaseTrainingCandidate = (id, overrideComment) => request(`/api/admin/base-training/experiments/${id}/select-candidate`, { method: 'POST', body: JSON.stringify(overrideComment ? { override_comment: overrideComment } : {}) })
export const baseTrainingCandidate = (id) => request(`/api/admin/base-training/experiments/${id}/candidate`)
export const baseTrainingManifest = (id) => request(`/api/admin/base-training/experiments/${id}/manifest`)
export const verifyBaseTrainingManifest = (id) => request(`/api/admin/base-training/experiments/${id}/manifest/verify`, { method: 'POST' })

export const instructionTuningExperiments = (query = '') => request(`/api/admin/instruction-tuning/experiments${query}`)
export const createInstructionTuningExperiment = (body) => request('/api/admin/instruction-tuning/experiments', { method: 'POST', body: JSON.stringify(body) })
export const instructionTuningExperiment = (id) => request(`/api/admin/instruction-tuning/experiments/${id}`)
export const patchInstructionTuningExperiment = (id, body) => request(`/api/admin/instruction-tuning/experiments/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const generateInstructionTuningProfile = (id) => request(`/api/admin/instruction-tuning/experiments/${id}/profile`, { method: 'POST' })
export const instructionTuningProfile = (id) => request(`/api/admin/instruction-tuning/experiments/${id}/profile`)
export const instructionTuningTemplates = () => request('/api/admin/instruction-tuning/templates')
export const createInstructionTuningTemplate = (body) => request('/api/admin/instruction-tuning/templates', { method: 'POST', body: JSON.stringify(body) })
export const instructionTuningTemplate = (id) => request(`/api/admin/instruction-tuning/templates/${id}`)
export const validateInstructionTuningTemplate = (id) => request(`/api/admin/instruction-tuning/templates/${id}/validate`, { method: 'POST' })
export const createInstructionTuningRun = (id, body) => request(`/api/admin/instruction-tuning/experiments/${id}/runs`, { method: 'POST', body: JSON.stringify(body) })
export const instructionTuningRuns = (id) => request(`/api/admin/instruction-tuning/experiments/${id}/runs`)
export const instructionTuningRun = (runId) => request(`/api/admin/instruction-tuning/runs/${runId}`)
export const queueInstructionTuningRun = (runId) => request(`/api/admin/instruction-tuning/runs/${runId}/queue`, { method: 'POST' })
export const evaluateInstructionTuningRun = (runId) => request(`/api/admin/instruction-tuning/runs/${runId}/evaluate`, { method: 'POST' })
export const instructionTuningMetrics = (runId) => request(`/api/admin/instruction-tuning/runs/${runId}/metrics`)
export const instructionTuningLanguageMetrics = (runId) => request(`/api/admin/instruction-tuning/runs/${runId}/language-metrics`)
export const instructionTuningLearningChecks = (runId) => request(`/api/admin/instruction-tuning/runs/${runId}/learning-checks`)
export const diagnosticGenerate = (runId, promptText, maxNewTokens) => request(`/api/admin/instruction-tuning/runs/${runId}/diagnostic-generate`, { method: 'POST', body: JSON.stringify({ prompt_text: promptText, max_new_tokens: maxNewTokens }) })
export const compareInstructionTuningRuns = (id, left, right) => request(`/api/admin/instruction-tuning/experiments/${id}/compare-runs`, { method: 'POST', body: JSON.stringify({ left_run_public_id: left, right_run_public_id: right }) })
export const instructionTuningComparisons = (id) => request(`/api/admin/instruction-tuning/experiments/${id}/comparisons`)
export const selectInstructionTuningCandidate = (id, overrideComment) => request(`/api/admin/instruction-tuning/experiments/${id}/select-candidate`, { method: 'POST', body: JSON.stringify(overrideComment ? { override_comment: overrideComment } : {}) })
export const instructionTuningCandidate = (id) => request(`/api/admin/instruction-tuning/experiments/${id}/candidate`)
export const instructionTuningManifest = (id) => request(`/api/admin/instruction-tuning/experiments/${id}/manifest`)
export const verifyInstructionTuningManifest = (id) => request(`/api/admin/instruction-tuning/experiments/${id}/manifest/verify`, { method: 'POST' })

export const evalCandidates = () => request('/api/admin/model-evaluation/candidates')
export const evalSuites = () => request('/api/admin/model-evaluation/suites')
export const createEvalSuite = (body) => request('/api/admin/model-evaluation/suites', { method: 'POST', body: JSON.stringify(body) })
export const evalSuite = (id) => request(`/api/admin/model-evaluation/suites/${id}`)
export const patchEvalSuite = (id, body) => request(`/api/admin/model-evaluation/suites/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const validateEvalSuite = (id) => request(`/api/admin/model-evaluation/suites/${id}/validate`, { method: 'POST' })
export const activateEvalSuite = (id) => request(`/api/admin/model-evaluation/suites/${id}/activate`, { method: 'POST' })
export const evalFixtureSets = (suiteId) => request(`/api/admin/model-evaluation/suites/${suiteId}/fixture-sets`)
export const createEvalFixtureSet = (suiteId, body) => request(`/api/admin/model-evaluation/suites/${suiteId}/fixture-sets`, { method: 'POST', body: JSON.stringify(body) })
export const evalFixtureSet = (id) => request(`/api/admin/model-evaluation/fixture-sets/${id}`)
export const evalFixtureSetCoverage = (id) => request(`/api/admin/model-evaluation/fixture-sets/${id}/coverage`)
export const evalFixtures = (fixtureSetId) => request(`/api/admin/model-evaluation/fixture-sets/${fixtureSetId}/fixtures`)
export const evalRuns = () => request('/api/admin/model-evaluation/runs')
export const createEvalRun = (body) => request('/api/admin/model-evaluation/runs', { method: 'POST', body: JSON.stringify(body) })
export const evalRun = (runId) => request(`/api/admin/model-evaluation/runs/${runId}`)
export const executeEvalRun = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/execute`, { method: 'POST' })
export const evalOutputs = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/outputs`)
export const evalMetrics = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/metrics`)
export const evalIssues = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/issues`)
export const submitEvalHumanReview = (body) => request('/api/admin/model-evaluation/human-reviews', { method: 'POST', body: JSON.stringify(body) })
export const evalReviewQueue = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/review-queue`)
export const evalReviews = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/reviews`)
export const assessEvalReadiness = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/assess-readiness`, { method: 'POST' })
export const evalReadiness = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/readiness`)
export const compareEvalRuns = (left, right) => request('/api/admin/model-evaluation/comparisons', { method: 'POST', body: JSON.stringify({ left_run_public_id: left, right_run_public_id: right }) })
export const generateEvalManifest = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/manifest`, { method: 'POST' })
export const verifyEvalManifest = (runId) => request(`/api/admin/model-evaluation/runs/${runId}/manifest/verify`, { method: 'POST' })

export const releaseFamilies = () => request('/api/admin/model-releases/families')
export const createReleaseFamily = (body) => request('/api/admin/model-releases/families', { method: 'POST', body: JSON.stringify(body) })
export const releaseFamily = (id) => request(`/api/admin/model-releases/families/${id}`)
export const patchReleaseFamily = (id, body) => request(`/api/admin/model-releases/families/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const releaseCandidates = () => request('/api/admin/model-releases/candidates')
export const createReleaseCandidate = (body) => request('/api/admin/model-releases/candidates', { method: 'POST', body: JSON.stringify(body) })
export const releaseCandidate = (id) => request(`/api/admin/model-releases/candidates/${id}`)
export const collectReleaseArtifacts = (id) => request(`/api/admin/model-releases/candidates/${id}/collect-artifacts`, { method: 'POST' })
export const verifyReleaseArtifacts = (id) => request(`/api/admin/model-releases/candidates/${id}/verify-artifacts`, { method: 'POST' })
export const assessReleaseEligibility = (id) => request(`/api/admin/model-releases/candidates/${id}/eligibility/assess`, { method: 'POST' })
export const releaseEligibility = (id) => request(`/api/admin/model-releases/candidates/${id}/eligibility`)
export const releaseIssues = (id) => request(`/api/admin/model-releases/candidates/${id}/issues`)
export const createReleaseModelCard = (id) => request(`/api/admin/model-releases/candidates/${id}/model-card`, { method: 'POST' })
export const releaseModelCard = (id) => request(`/api/admin/model-releases/candidates/${id}/model-card`)
export const validateReleaseModelCard = (id) => request(`/api/admin/model-releases/candidates/${id}/model-card/validate`, { method: 'POST' })
export const createReleaseManifest = (id) => request(`/api/admin/model-releases/candidates/${id}/manifest`, { method: 'POST' })
export const releaseManifest = (id) => request(`/api/admin/model-releases/candidates/${id}/manifest`)
export const verifyReleaseManifest = (id) => request(`/api/admin/model-releases/candidates/${id}/manifest/verify`, { method: 'POST' })
export const submitReleaseApproval = (id, body) => request(`/api/admin/model-releases/candidates/${id}/approvals`, { method: 'POST', body: JSON.stringify(body) })
export const releaseApprovals = (id) => request(`/api/admin/model-releases/candidates/${id}/approvals`)
export const releases = () => request('/api/admin/model-releases/releases')
export const createRelease = (body) => request('/api/admin/model-releases/releases', { method: 'POST', body: JSON.stringify(body) })
export const release = (id) => request(`/api/admin/model-releases/releases/${id}`)
export const deprecateRelease = (id) => request(`/api/admin/model-releases/releases/${id}/deprecate`, { method: 'POST' })
export const retireRelease = (id) => request(`/api/admin/model-releases/releases/${id}/retire`, { method: 'POST' })
export const compareReleases = (left, right) => request('/api/admin/model-releases/releases/compare', { method: 'POST', body: JSON.stringify({ left_release_public_id: left, right_release_public_id: right }) })
export const releaseComparison = (id) => request(`/api/admin/model-releases/comparisons/${id}`)
export const buildReleaseBundle = (id) => request(`/api/admin/model-releases/releases/${id}/bundle`, { method: 'POST' })
export const releaseBundles = (id) => request(`/api/admin/model-releases/releases/${id}/bundles`)
export const verifyReleaseBundle = (id) => request(`/api/admin/model-releases/bundles/${id}/verify`, { method: 'POST' })
export const createRollbackPlan = (releaseId, body) => request(`/api/admin/model-releases/releases/${releaseId}/rollback-plans`, { method: 'POST', body: JSON.stringify(body) })
export const rollbackPlan = (id) => request(`/api/admin/model-releases/rollback-plans/${id}`)
export const validateRollbackPlan = (id) => request(`/api/admin/model-releases/rollback-plans/${id}/validate`, { method: 'POST' })
export const approveRollbackPlan = (id) => request(`/api/admin/model-releases/rollback-plans/${id}/approve`, { method: 'POST' })
export const executeRollbackPlan = (id) => request(`/api/admin/model-releases/rollback-plans/${id}/execute`, { method: 'POST' })

const IR = '/api/admin/inference-runtime'
export const runtimeProfiles = () => request(`${IR}/profiles`)
export const createRuntimeProfile = (body) => request(`${IR}/profiles`, { method: 'POST', body: JSON.stringify(body) })
export const runtimeProfile = (id) => request(`${IR}/profiles/${id}`)
export const patchRuntimeProfile = (id, body) => request(`${IR}/profiles/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const runtimeInstances = () => request(`${IR}/instances`)
export const createRuntimeInstance = (runtimeProfilePublicId) => request(`${IR}/instances`, { method: 'POST', body: JSON.stringify({ runtime_profile_public_id: runtimeProfilePublicId }) })
export const runtimeInstance = (id) => request(`${IR}/instances/${id}`)
export const startRuntimeInstance = (id) => request(`${IR}/instances/${id}/start`, { method: 'POST' })
export const stopRuntimeInstance = (id) => request(`${IR}/instances/${id}/stop`, { method: 'POST' })
export const loadRuntimeInstance = (id, releasePublicId) => request(`${IR}/instances/${id}/load`, { method: 'POST', body: JSON.stringify({ release_public_id: releasePublicId }) })
export const unloadRuntimeInstance = (id) => request(`${IR}/instances/${id}/unload`, { method: 'POST' })
export const runtimeInstanceHealthCheck = (id) => request(`${IR}/instances/${id}/health-check`, { method: 'POST' })
export const assessRuntimeCompatibility = (releaseId, runtimeProfilePublicId) => request(`${IR}/releases/${releaseId}/compatibility/assess`, { method: 'POST', body: JSON.stringify({ runtime_profile_public_id: runtimeProfilePublicId }) })
export const runtimeCompatibility = (releaseId) => request(`${IR}/releases/${releaseId}/compatibility`)
export const assignmentScopes = () => request(`${IR}/assignment-scopes`)
export const assignments = () => request(`${IR}/assignments`)
export const createAssignment = (body) => request(`${IR}/assignments`, { method: 'POST', body: JSON.stringify(body) })
export const assignment = (id) => request(`${IR}/assignments/${id}`)
export const patchAssignment = (id, body) => request(`${IR}/assignments/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const validateAssignment = (id) => request(`${IR}/assignments/${id}/validate`, { method: 'POST' })
export const approveAssignment = (id, body) => request(`${IR}/assignments/${id}/approve`, { method: 'POST', body: JSON.stringify(body) })
export const activateAssignment = (id, explicitActivationConfirmed = false) => request(`${IR}/assignments/${id}/activate`, { method: 'POST', body: JSON.stringify({ explicit_activation_confirmed: explicitActivationConfirmed }) })
export const pauseAssignment = (id) => request(`${IR}/assignments/${id}/pause`, { method: 'POST' })
export const resumeAssignment = (id) => request(`${IR}/assignments/${id}/resume`, { method: 'POST' })
export const assignmentVersions = (id) => request(`${IR}/assignments/${id}/versions`)
export const assignmentEvents = (id) => request(`${IR}/assignments/${id}/events`)
export const runtimeDiagnosticGenerate = (id, body) => request(`${IR}/assignments/${id}/diagnostic-generate`, { method: 'POST', body: JSON.stringify(body) })
export const createChatLabSession = (id, body) => request(`${IR}/assignments/${id}/sessions`, { method: 'POST', body: JSON.stringify(body) })
export const chatLabSession = (id) => request(`${IR}/sessions/${id}`)
export const postChatLabMessage = (id, message) => request(`${IR}/sessions/${id}/messages`, { method: 'POST', body: JSON.stringify({ message }) })
export const closeChatLabSession = (id) => request(`${IR}/sessions/${id}/close`, { method: 'POST' })
export const startCanary = (id, body) => request(`${IR}/assignments/${id}/canary/start`, { method: 'POST', body: JSON.stringify(body) })
export const executeCanary = (id, fixturePrompts) => request(`${IR}/assignments/${id}/canary/execute`, { method: 'POST', body: JSON.stringify({ fixture_prompts: fixturePrompts }) })
export const stopCanary = (id, reason = 'admin_stop') => request(`${IR}/assignments/${id}/canary/stop`, { method: 'POST', body: JSON.stringify({ reason }) })
export const canaryResults = (id) => request(`${IR}/assignments/${id}/canary/results`)
export const rollbackPreview = (id, targetVersionPublicId) => request(`${IR}/assignments/${id}/rollback/preview`, { method: 'POST', body: JSON.stringify({ target_version_public_id: targetVersionPublicId }) })
export const rollbackExecute = (id, targetVersionPublicId) => request(`${IR}/assignments/${id}/rollback/execute`, { method: 'POST', body: JSON.stringify({ target_version_public_id: targetVersionPublicId }) })
export const runtimeManifest = (id) => request(`${IR}/assignments/${id}/manifest`)
export const verifyRuntimeManifest = (id) => request(`${IR}/assignments/${id}/manifest/verify`, { method: 'POST' })

const RAG = '/api/admin/rag'
export const ragSpaces = () => request(`${RAG}/spaces`)
export const createRagSpace = (body) => request(`${RAG}/spaces`, { method: 'POST', body: JSON.stringify(body) })
export const ragSpace = (id) => request(`${RAG}/spaces/${id}`)
export const patchRagSpace = (id, body) => request(`${RAG}/spaces/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const ragSources = (spaceId) => request(`${RAG}/spaces/${spaceId}/sources`)
export const createRagSource = (spaceId, body) => request(`${RAG}/spaces/${spaceId}/sources`, { method: 'POST', body: JSON.stringify(body) })
export const ragSource = (id) => request(`${RAG}/sources/${id}`)
export const patchRagSource = (id, body) => request(`${RAG}/sources/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const ragSourceVersions = (sourceId) => request(`${RAG}/sources/${sourceId}/versions`)
export const createRagSourceVersion = (sourceId) => request(`${RAG}/sources/${sourceId}/versions`, { method: 'POST' })
export const ragSourceVersion = (id) => request(`${RAG}/versions/${id}`)
export const validateRagSourceVersion = (id) => request(`${RAG}/versions/${id}/validate`, { method: 'POST' })
export const ragChunkSets = (versionId) => request(`${RAG}/versions/${versionId}/chunk-sets`)
export const createRagChunkSet = (versionId, body) => request(`${RAG}/versions/${versionId}/chunk-sets`, { method: 'POST', body: JSON.stringify(body) })
export const ragChunkSet = (id) => request(`${RAG}/chunk-sets/${id}`)
export const ragChunks = (chunkSetId) => request(`${RAG}/chunk-sets/${chunkSetId}/chunks`)
export const validateRagChunkSet = (id) => request(`${RAG}/chunk-sets/${id}/validate`, { method: 'POST' })
export const ragEmbeddingModels = () => request(`${RAG}/embedding-models`)
export const createRagEmbeddingModel = (body) => request(`${RAG}/embedding-models`, { method: 'POST', body: JSON.stringify(body) })
export const createRagEmbeddingRun = (chunkSetId, body) => request(`${RAG}/chunk-sets/${chunkSetId}/embedding-runs`, { method: 'POST', body: JSON.stringify(body) })
export const ragEmbeddingRun = (id) => request(`${RAG}/embedding-runs/${id}`)
export const executeRagEmbeddingRun = (id) => request(`${RAG}/embedding-runs/${id}/execute`, { method: 'POST' })
export const verifyRagEmbeddingRun = (id) => request(`${RAG}/embedding-runs/${id}/verify`)
export const createRagVectorIndex = (embeddingRunId, body = {}) => request(`${RAG}/embedding-runs/${embeddingRunId}/vector-index`, { method: 'POST', body: JSON.stringify(body) })
export const ragVectorIndex = (id) => request(`${RAG}/vector-indexes/${id}`)
export const buildRagVectorIndex = (id) => request(`${RAG}/vector-indexes/${id}/build`, { method: 'POST' })
export const validateRagVectorIndex = (id) => request(`${RAG}/vector-indexes/${id}/validate`, { method: 'POST' })
export const activateRagVectorIndex = (id) => request(`${RAG}/vector-indexes/${id}/activate`, { method: 'POST' })
export const createRagKeywordIndex = (chunkSetId, body = {}) => request(`${RAG}/chunk-sets/${chunkSetId}/keyword-index`, { method: 'POST', body: JSON.stringify(body) })
export const ragKeywordIndex = (id) => request(`${RAG}/keyword-indexes/${id}`)
export const buildRagKeywordIndex = (id) => request(`${RAG}/keyword-indexes/${id}/build`, { method: 'POST' })
export const validateRagKeywordIndex = (id) => request(`${RAG}/keyword-indexes/${id}/validate`, { method: 'POST' })
export const activateRagKeywordIndex = (id) => request(`${RAG}/keyword-indexes/${id}/activate`, { method: 'POST' })
export const ragRetrievalProfiles = () => request(`${RAG}/retrieval-profiles`)
export const createRagRetrievalProfile = (spaceId, body) => request(`${RAG}/spaces/${spaceId}/retrieval-profiles`, { method: 'POST', body: JSON.stringify(body) })
export const ragRetrievalProfile = (id) => request(`${RAG}/retrieval-profiles/${id}`)
export const patchRagRetrievalProfile = (id, body) => request(`${RAG}/retrieval-profiles/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const validateRagRetrievalProfile = (id) => request(`${RAG}/retrieval-profiles/${id}/validate`, { method: 'POST' })
export const activateRagRetrievalProfile = (id) => request(`${RAG}/retrieval-profiles/${id}/activate`, { method: 'POST' })
export const ragRetrieve = (body) => request(`${RAG}/retrieve`, { method: 'POST', body: JSON.stringify(body) })
export const ragRetrievalRun = (id) => request(`${RAG}/retrieval-runs/${id}`)
export const ragRetrievalResults = (id) => request(`${RAG}/retrieval-runs/${id}/results`)
export const ragGroundedAnswer = (body) => request(`${RAG}/grounded-answer`, { method: 'POST', body: JSON.stringify(body) })
export const ragGroundedRequest = (id) => request(`${RAG}/grounded-requests/${id}`)
export const ragGroundedAnswerResult = (id) => request(`${RAG}/grounded-requests/${id}/answer`)
export const ragGroundedCitations = (id) => request(`${RAG}/grounded-requests/${id}/citations`)
export const ragGroundedIssues = (id) => request(`${RAG}/grounded-requests/${id}/issues`)
export const createRagChatLabSession = (body) => request(`${RAG}/chat-lab/sessions`, { method: 'POST', body: JSON.stringify(body) })
export const ragChatLabSession = (id) => request(`${RAG}/chat-lab/sessions/${id}`)
export const postRagChatLabMessage = (id, message, retrievalProfilePublicId) => request(`${RAG}/chat-lab/sessions/${id}/messages`, { method: 'POST', body: JSON.stringify({ message, retrieval_profile_public_id: retrievalProfilePublicId }) })
export const closeRagChatLabSession = (id) => request(`${RAG}/chat-lab/sessions/${id}/close`, { method: 'POST' })
export const ragEvaluationSuites = () => request(`${RAG}/evaluation-suites`)
export const createRagEvaluationSuite = (spaceId, body) => request(`${RAG}/spaces/${spaceId}/evaluation-suites`, { method: 'POST', body: JSON.stringify(body) })
export const ragEvaluationSuite = (id) => request(`${RAG}/evaluation-suites/${id}`)
export const addRagEvaluationFixture = (suiteId, body) => request(`${RAG}/evaluation-suites/${suiteId}/fixtures`, { method: 'POST', body: JSON.stringify(body) })
export const createRagEvaluationRun = (suiteId, body) => request(`${RAG}/evaluation-suites/${suiteId}/runs`, { method: 'POST', body: JSON.stringify(body) })
export const ragEvaluationRun = (id) => request(`${RAG}/evaluation-runs/${id}`)
export const executeRagEvaluationRun = (id) => request(`${RAG}/evaluation-runs/${id}/execute`, { method: 'POST' })
export const ragEvaluationMetrics = (id) => request(`${RAG}/evaluation-runs/${id}/metrics`)
export const createRagIndexComparison = (body) => request(`${RAG}/index-comparisons`, { method: 'POST', body: JSON.stringify(body) })
export const ragIndexComparison = (id) => request(`${RAG}/index-comparisons/${id}`)
export const generateRagManifest = (spaceId) => request(`${RAG}/spaces/${spaceId}/manifest`, { method: 'POST' })
export const verifyRagManifest = (spaceId) => request(`${RAG}/spaces/${spaceId}/manifest/verify`)

const CM = '/api/admin/conversation-memory'
export const memoryPolicies = () => request(`${CM}/policies`)
export const createMemoryPolicy = (body) => request(`${CM}/policies`, { method: 'POST', body: JSON.stringify(body) })
export const memoryPolicy = (id) => request(`${CM}/policies/${id}`)
export const patchMemoryPolicy = (id, body) => request(`${CM}/policies/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const validateMemoryPolicy = (id) => request(`${CM}/policies/${id}/validate`, { method: 'POST' })
export const activateMemoryPolicy = (id) => request(`${CM}/policies/${id}/activate`, { method: 'POST' })
export const conversationSessions = () => request(`${CM}/sessions`)
export const createConversationSession = (body) => request(`${CM}/sessions`, { method: 'POST', body: JSON.stringify(body) })
export const conversationSession = (id) => request(`${CM}/sessions/${id}`)
export const pauseConversationSession = (id) => request(`${CM}/sessions/${id}/pause`, { method: 'POST' })
export const resumeConversationSession = (id) => request(`${CM}/sessions/${id}/resume`, { method: 'POST' })
export const closeConversationSession = (id) => request(`${CM}/sessions/${id}/close`, { method: 'POST' })
export const expireConversationSession = (id) => request(`${CM}/sessions/${id}/expire`, { method: 'POST' })
export const conversationSessionTurns = (id) => request(`${CM}/sessions/${id}/turns`)
export const postConversationMessage = (id, body) => request(`${CM}/sessions/${id}/messages`, { method: 'POST', body: JSON.stringify(body) })
export const orchestrationRun = (id) => request(`${CM}/orchestration-runs/${id}`)
export const orchestrationContext = (id) => request(`${CM}/orchestration-runs/${id}/context`)
export const orchestrationResponse = (id) => request(`${CM}/orchestration-runs/${id}/response`)
export const orchestrationIssues = (id) => request(`${CM}/orchestration-runs/${id}/issues`)
export const createConversationSummary = (sessionId, body = {}) => request(`${CM}/sessions/${sessionId}/summaries`, { method: 'POST', body: JSON.stringify(body) })
export const conversationSummaries = (sessionId) => request(`${CM}/sessions/${sessionId}/summaries`)
export const conversationSummary = (id) => request(`${CM}/summaries/${id}`)
export const validateConversationSummary = (id) => request(`${CM}/summaries/${id}/validate`, { method: 'POST' })
export const acceptConversationSummary = (id) => request(`${CM}/summaries/${id}/accept`, { method: 'POST' })
export const rejectConversationSummary = (id) => request(`${CM}/summaries/${id}/reject`, { method: 'POST' })
export const memoryConsents = () => request(`${CM}/consents`)
export const createMemoryConsent = (body) => request(`${CM}/consents`, { method: 'POST', body: JSON.stringify(body) })
export const memoryConsent = (id) => request(`${CM}/consents/${id}`)
export const revokeMemoryConsent = (id) => request(`${CM}/consents/${id}/revoke`, { method: 'POST' })
export const expireMemoryConsent = (id) => request(`${CM}/consents/${id}/expire`, { method: 'POST' })
export const memoryItems = (participantScopeKey) => request(`${CM}/memory-items${participantScopeKey ? `?participant_scope_key=${encodeURIComponent(participantScopeKey)}` : ''}`)
export const createMemoryItem = (body) => request(`${CM}/memory-items`, { method: 'POST', body: JSON.stringify(body) })
export const memoryItem = (id) => request(`${CM}/memory-items/${id}`)
export const confirmMemoryItem = (id) => request(`${CM}/memory-items/${id}/confirm`, { method: 'POST' })
export const rejectMemoryItem = (id) => request(`${CM}/memory-items/${id}/reject`, { method: 'POST' })
export const correctMemoryItem = (id, body) => request(`${CM}/memory-items/${id}/correct`, { method: 'POST', body: JSON.stringify(body) })
export const expireMemoryItem = (id) => request(`${CM}/memory-items/${id}/expire`, { method: 'POST' })
export const deleteMemoryItem = (id) => request(`${CM}/memory-items/${id}/delete`, { method: 'POST' })
export const memoryItemVersions = (id) => request(`${CM}/memory-items/${id}/versions`)
export const memoryItemEvents = (id) => request(`${CM}/memory-items/${id}/events`)
export const memoryRetrievalProfiles = () => request(`${CM}/retrieval-profiles`)
export const createMemoryRetrievalProfile = (body) => request(`${CM}/retrieval-profiles`, { method: 'POST', body: JSON.stringify(body) })
export const memoryRetrievalProfile = (id) => request(`${CM}/retrieval-profiles/${id}`)
export const validateMemoryRetrievalProfile = (id) => request(`${CM}/retrieval-profiles/${id}/validate`, { method: 'POST' })
export const activateMemoryRetrievalProfile = (id) => request(`${CM}/retrieval-profiles/${id}/activate`, { method: 'POST' })
export const retrieveMemory = (body) => request(`${CM}/retrieve`, { method: 'POST', body: JSON.stringify(body) })
export const memoryRetrievalRun = (id) => request(`${CM}/retrieval-runs/${id}`)
export const memoryRetrievalResults = (id) => request(`${CM}/retrieval-runs/${id}/results`)
export const memoryEvaluationSuites = () => request(`${CM}/evaluation-suites`)
export const createMemoryEvaluationSuite = (body) => request(`${CM}/evaluation-suites`, { method: 'POST', body: JSON.stringify(body) })
export const addMemoryEvaluationFixture = (suiteId, body) => request(`${CM}/evaluation-suites/${suiteId}/fixtures`, { method: 'POST', body: JSON.stringify(body) })
export const createMemoryEvaluationRun = (suiteId, body) => request(`${CM}/evaluation-suites/${suiteId}/runs`, { method: 'POST', body: JSON.stringify(body) })
export const executeMemoryEvaluationRun = (id) => request(`${CM}/evaluation-runs/${id}/execute`, { method: 'POST' })
export const memoryEvaluationRun = (id) => request(`${CM}/evaluation-runs/${id}`)
export const memoryEvaluationMetrics = (id) => request(`${CM}/evaluation-runs/${id}/metrics`)
export const generateMemoryManifest = (policyId) => request(`${CM}/policies/${policyId}/manifest`, { method: 'POST' })
export const verifyMemoryManifest = (policyId) => request(`${CM}/policies/${policyId}/manifest/verify`)

const FB = '/api/admin/feedback'
export const feedbackPolicies = () => request(`${FB}/policies`)
export const createFeedbackPolicy = (body) => request(`${FB}/policies`, { method: 'POST', body: JSON.stringify(body) })
export const feedbackPolicy = (id) => request(`${FB}/policies/${id}`)
export const patchFeedbackPolicy = (id, body) => request(`${FB}/policies/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const validateFeedbackPolicy = (id) => request(`${FB}/policies/${id}/validate`, { method: 'POST' })
export const activateFeedbackPolicy = (id) => request(`${FB}/policies/${id}/activate`, { method: 'POST' })

export const feedbackEvents = (participantScopeKey) => request(`${FB}/events${participantScopeKey ? `?participant_scope_key=${encodeURIComponent(participantScopeKey)}` : ''}`)
export const submitFeedbackEvent = (body) => request(`${FB}/events`, { method: 'POST', body: JSON.stringify(body) })
export const feedbackEvent = (id) => request(`${FB}/events/${id}`)
export const triageFeedbackEvent = (id) => request(`${FB}/events/${id}/triage`, { method: 'POST' })
export const deleteFeedbackEvent = (id) => request(`${FB}/events/${id}/delete`, { method: 'POST' })
export const feedbackClassifications = (id) => request(`${FB}/events/${id}/classifications`)
export const addFeedbackClassification = (id, body) => request(`${FB}/events/${id}/classifications`, { method: 'POST', body: JSON.stringify(body) })
export const feedbackFindings = (id) => request(`${FB}/events/${id}/findings`)

export const reviewQueues = () => request(`${FB}/review-queues`)
export const createReviewQueue = (body) => request(`${FB}/review-queues`, { method: 'POST', body: JSON.stringify(body) })
export const reviewQueue = (id) => request(`${FB}/review-queues/${id}`)
export const assignReview = (queueId, body) => request(`${FB}/review-queues/${queueId}/assign`, { method: 'POST', body: JSON.stringify(body) })
export const reviewQueueItems = (queueId) => request(`${FB}/review-queues/${queueId}/items`)

export const createFeedbackReview = (eventId, body) => request(`${FB}/events/${eventId}/reviews`, { method: 'POST', body: JSON.stringify(body) })
export const feedbackReviews = (eventId) => request(`${FB}/events/${eventId}/reviews`)
export const feedbackReviewSummary = (eventId) => request(`${FB}/events/${eventId}/review-summary`)

export const createCorrectedResponse = (eventId, body) => request(`${FB}/events/${eventId}/corrected-responses`, { method: 'POST', body: JSON.stringify(body) })
export const correctedResponsesForEvent = (eventId) => request(`${FB}/events/${eventId}/corrected-responses`)
export const correctedResponse = (id) => request(`${FB}/corrected-responses/${id}`)
export const validateCorrectedResponse = (id) => request(`${FB}/corrected-responses/${id}/validate`, { method: 'POST' })
export const rejectCorrectedResponse = (id) => request(`${FB}/corrected-responses/${id}/reject`, { method: 'POST' })

export const datasetCandidates = () => request(`${FB}/dataset-candidates`)
export const createDatasetCandidate = (eventId, body) => request(`${FB}/events/${eventId}/dataset-candidates`, { method: 'POST', body: JSON.stringify(body) })
export const datasetCandidate = (id) => request(`${FB}/dataset-candidates/${id}`)
export const validateDatasetCandidate = (id) => request(`${FB}/dataset-candidates/${id}/validate`, { method: 'POST' })
export const approveDatasetCandidate = (id, body) => request(`${FB}/dataset-candidates/${id}/approve`, { method: 'POST', body: JSON.stringify(body || {}) })
export const rejectDatasetCandidate = (id, body) => request(`${FB}/dataset-candidates/${id}/reject`, { method: 'POST', body: JSON.stringify(body || {}) })
export const quarantineDatasetCandidate = (id, body) => request(`${FB}/dataset-candidates/${id}/quarantine`, { method: 'POST', body: JSON.stringify(body || {}) })
export const datasetCandidateVersions = (id) => request(`${FB}/dataset-candidates/${id}/versions`)
export const datasetCandidateIssues = (id) => request(`${FB}/dataset-candidates/${id}/issues`)
export const exportDatasetCandidate = (id) => request(`${FB}/dataset-candidates/${id}/export`, { method: 'POST' })

export const regressionSuites = () => request(`${FB}/regression-suites`)
export const createRegressionSuite = (body) => request(`${FB}/regression-suites`, { method: 'POST', body: JSON.stringify(body) })
export const regressionSuite = (id) => request(`${FB}/regression-suites/${id}`)
export const addRegressionFixture = (suiteId, body) => request(`${FB}/regression-suites/${suiteId}/fixtures`, { method: 'POST', body: JSON.stringify(body) })
export const validateRegressionSuite = (id) => request(`${FB}/regression-suites/${id}/validate`, { method: 'POST' })
export const activateRegressionSuite = (id) => request(`${FB}/regression-suites/${id}/activate`, { method: 'POST' })

export const createRegressionRun = (suiteId, body) => request(`${FB}/regression-suites/${suiteId}/runs`, { method: 'POST', body: JSON.stringify(body) })
export const executeRegressionRun = (id) => request(`${FB}/regression-runs/${id}/execute`, { method: 'POST' })
export const regressionRun = (id) => request(`${FB}/regression-runs/${id}`)
export const regressionResults = (id) => request(`${FB}/regression-runs/${id}/results`)
export const regressionMetrics = (id) => request(`${FB}/regression-runs/${id}/metrics`)

export const compareRegressionRuns = (body) => request(`${FB}/regression-runs/compare`, { method: 'POST', body: JSON.stringify(body) })
export const comparison = (id) => request(`${FB}/comparisons/${id}`)
export const createImprovementReport = (body) => request(`${FB}/improvement-reports`, { method: 'POST', body: JSON.stringify(body || {}) })
export const improvementReport = (id) => request(`${FB}/improvement-reports/${id}`)

export const feedbackManifest = (policyId) => request(`${FB}/policies/${policyId}/manifest`)
export const verifyFeedbackManifest = (policyId) => request(`${FB}/policies/${policyId}/manifest/verify`, { method: 'POST' })

const CORPUS = '/api/admin/corpus'
export const corpusPolicies = () => request(`${CORPUS}/policies`)
export const createCorpusPolicy = (body) => request(`${CORPUS}/policies`, { method: 'POST', body: JSON.stringify(body) })
export const corpusPolicy = (id) => request(`${CORPUS}/policies/${id}`)
export const patchCorpusPolicy = (id, body) => request(`${CORPUS}/policies/${id}`, { method: 'PATCH', body: JSON.stringify(body) })

export const corpusSources = () => request(`${CORPUS}/sources`)
export const createCorpusSource = (body) => request(`${CORPUS}/sources`, { method: 'POST', body: JSON.stringify(body) })
export const corpusSource = (id) => request(`${CORPUS}/sources/${id}`)
export const patchCorpusSource = (id, body) => request(`${CORPUS}/sources/${id}`, { method: 'PATCH', body: JSON.stringify(body) })
export const transitionCorpusSource = (id, body) => request(`${CORPUS}/sources/${id}/transition`, { method: 'POST', body: JSON.stringify(body) })
export const verifyCorpusSourceOrigin = (id, body) => request(`${CORPUS}/sources/${id}/verify-origin`, { method: 'POST', body: JSON.stringify(body) })
export const corpusSourceTrainingEligibility = (id) => request(`${CORPUS}/sources/${id}/training-eligibility`)

export const createCorpusLicence = (sourceId, body) => request(`${CORPUS}/sources/${sourceId}/licences`, { method: 'POST', body: JSON.stringify(body) })
export const reviewCorpusLicence = (id, body) => request(`${CORPUS}/licences/${id}/review`, { method: 'POST', body: JSON.stringify(body) })

export const createCorpusSnapshot = (sourceId, body) => request(`${CORPUS}/sources/${sourceId}/snapshots`, { method: 'POST', body: JSON.stringify(body) })
export const corpusSnapshotsForSource = (sourceId) => request(`${CORPUS}/sources/${sourceId}/snapshots`)
export const corpusSnapshot = (id) => request(`${CORPUS}/snapshots/${id}`)

export const createCorpusExtractionRun = (snapshotId, body) => request(`${CORPUS}/snapshots/${snapshotId}/extraction-runs`, { method: 'POST', body: JSON.stringify(body) })
export const corpusExtractionRun = (id) => request(`${CORPUS}/extraction-runs/${id}`)

export const createCorpusNormalizationRun = (extractionRunId, body) => request(`${CORPUS}/extraction-runs/${extractionRunId}/normalization-runs`, { method: 'POST', body: JSON.stringify(body || {}) })
export const corpusNormalizationRun = (id) => request(`${CORPUS}/normalization-runs/${id}`)

export const segmentCorpusDocument = (documentId, body) => request(`${CORPUS}/normalized-documents/${documentId}/segment`, { method: 'POST', body: JSON.stringify(body || {}) })

export const assessCorpusSegment = (id) => request(`${CORPUS}/segments/${id}/assess`, { method: 'POST' })

export const createCorpusDeduplicationRun = (body) => request(`${CORPUS}/deduplication-runs`, { method: 'POST', body: JSON.stringify(body || {}) })
export const corpusDeduplicationRun = (id) => request(`${CORPUS}/deduplication-runs/${id}`)

export const createCorpusContaminationRun = (body) => request(`${CORPUS}/contamination-runs`, { method: 'POST', body: JSON.stringify(body || {}) })
export const corpusContaminationRun = (id) => request(`${CORPUS}/contamination-runs/${id}`)

export const corpusCollections = () => request(`${CORPUS}/collections`)
export const createCorpusCollection = (body) => request(`${CORPUS}/collections`, { method: 'POST', body: JSON.stringify(body) })
export const corpusCollection = (id) => request(`${CORPUS}/collections/${id}`)
export const addCorpusCollectionMember = (id, body) => request(`${CORPUS}/collections/${id}/members`, { method: 'POST', body: JSON.stringify(body) })

export const corpusBalancePolicies = () => request(`${CORPUS}/balance-policies`)
export const createCorpusBalancePolicy = (body) => request(`${CORPUS}/balance-policies`, { method: 'POST', body: JSON.stringify(body) })

export const corpusBuilds = () => request(`${CORPUS}/builds`)
export const createCorpusBuild = (body) => request(`${CORPUS}/builds`, { method: 'POST', body: JSON.stringify(body) })
export const corpusBuild = (id) => request(`${CORPUS}/builds/${id}`)
export const corpusBuildBalanceReport = (id) => request(`${CORPUS}/builds/${id}/balance-report`)

export const corpusVersions = () => request(`${CORPUS}/versions`)
export const createCorpusVersion = (buildId, body) => request(`${CORPUS}/builds/${buildId}/versions`, { method: 'POST', body: JSON.stringify(body) })
export const corpusVersion = (id) => request(`${CORPUS}/versions/${id}`)

export const createCorpusExport = (versionId, body) => request(`${CORPUS}/versions/${versionId}/exports`, { method: 'POST', body: JSON.stringify(body || {}) })
export const corpusExport = (id) => request(`${CORPUS}/exports/${id}`)

export const generateCorpusManifest = (versionId) => request(`${CORPUS}/versions/${versionId}/manifest`, { method: 'POST' })
export const corpusManifest = (versionId) => request(`${CORPUS}/versions/${versionId}/manifest`)

export const compareCorpusVersions = (body) => request(`${CORPUS}/compare`, { method: 'POST', body: JSON.stringify(body) })
export const corpusComparison = (id) => request(`${CORPUS}/comparisons/${id}`)
