import Button from '../../components/Button.jsx'
import Skeleton from '../../components/Skeleton.jsx'
import StatusCard from '../../components/StatusCard.jsx'

const voSubTabs = [
  'Overview', 'Public Voice Chat', 'Admin Voice Assistant', 'Sessions', 'STT', 'TTS',
  'Permissions', 'Diagnostics', 'Metrics', 'Events', 'Memory', 'Settings', 'History',
]

export default function VoiceRuntimeTab({
  voSubTab, setVoSubTab,
  voDiag, voStats,
  voConsent, setVoConsent, voBusy, voRecording, startVoRecording, stopVoRecordingAndSend, voSessionData,
  voSelectedSessionId, selectVoSession, voSessionsList,
  runVoTestStt, voTestSttText,
  voTestTtsForm, setVoTestTtsForm, runVoTestTts, voTestTtsResult,
  voMetrics,
  voEventsList,
  voMemoryList,
}) {
  return (
    <>
      <p className="notice">
        MB-26 -- Voice &amp; Speech Runtime. Local-first speech-to-text and text-to-speech for
        Public Chat and the Admin Assistant, CPU-only, no GPU requirement. Microphone capture
        only ever runs while push-to-talk is actively held -- there is no wake-word listening,
        no background recording, and no cloud speech API by default. Public chat voice access
        requires explicit per-session consent; the Admin Assistant path requires real admin
        authorization. Every voice reply is generated by the same PublicChatRoutingService the
        text chat uses, and has already passed the existing text safety layer before it is
        ever spoken.
      </p>

      <div className="dataset-tabs">
        {voSubTabs.map((t) => (
          <Button key={t} className={voSubTab === t ? 'active' : ''} onClick={() => setVoSubTab(t)}>{t}</Button>
        ))}
      </div>

      {voSubTab === 'Overview' && (
        <>
          {voDiag && (
            <div className="notice">
              <p><strong>STT backend:</strong> {voDiag.stt_backend} ({voDiag.stt_available ? 'available' : 'unavailable, using mock'}) -- <strong>TTS backend:</strong> {voDiag.tts_backend} ({voDiag.tts_available ? 'available' : 'unavailable, using mock'})</p>
              <p><strong>Local only:</strong> {String(voDiag.local_only)} -- <strong>GPU required:</strong> {String(voDiag.gpu_required)} -- <strong>Wake-word enabled:</strong> {String(voDiag.wakeword_enabled)}</p>
              <p><strong>Max record seconds:</strong> {voDiag.max_record_seconds} -- <strong>Max audio MB:</strong> {voDiag.max_audio_mb}</p>
            </div>
          )}
          {voStats && (
            <section className="metric-grid">
              <StatusCard label="Total sessions" value={voStats.total_sessions} tone="neutral" />
              <StatusCard label="Completed" value={voStats.sessions_by_status?.completed || 0} tone="good" />
              <StatusCard label="Denied" value={voStats.sessions_by_status?.denied || 0} tone="warn" />
              <StatusCard label="Active" value={voStats.sessions_by_status?.active || 0} tone="neutral" />
            </section>
          )}
        </>
      )}

      {voSubTab === 'Public Voice Chat' && (
        <>
          <label>
            <input type="checkbox" checked={voConsent} onChange={(e) => setVoConsent(e.target.checked)} />
            {' '}I consent to microphone capture for this voice session
          </label>
          <div className="notice">
            <Button
              disabled={!voConsent || voBusy}
              className={voRecording ? 'active' : ''}
              onMouseDown={startVoRecording}
              onMouseUp={stopVoRecordingAndSend}
              onTouchStart={startVoRecording}
              onTouchEnd={stopVoRecordingAndSend}
            >
              {voRecording ? '● Recording -- release to send' : '🎤 Hold to talk'}
            </Button>
            {voRecording && <span className="notice"> Recording…</span>}
          </div>
          {voSessionData && (
            <div className="notice">
              <p><strong>Transcript:</strong> {voSessionData.transcript || '(none yet)'}</p>
              <p><strong>Reply:</strong> {voSessionData.reply || '(none yet)'}</p>
              {voSessionData.tts_audio_relative_path && (
                <p><strong>TTS output path:</strong> {voSessionData.tts_audio_relative_path}</p>
              )}
              {voSessionData.denial_reason && <p className="notice">Denied: {voSessionData.denial_reason}</p>}
            </div>
          )}
        </>
      )}

      {voSubTab === 'Admin Voice Assistant' && (
        <div className="notice">
          Admin Assistant voice access requires real admin authorization (the same session the
          dashboard is already logged into) -- there is no separate consent checkbox for this
          path, matching MB-26's admin-authorization-substitutes-for-consent design.
        </div>
      )}

      {voSubTab === 'Sessions' && (
        <>
          <select value={voSelectedSessionId} onChange={(e) => selectVoSession(e.target.value)}>
            <option value="">Select a session…</option>
            {voSessionsList.map((s) => (
              <option key={s.public_id} value={s.public_id}>{s.created_at} -- {s.session_mode} -- {s.status}</option>
            ))}
          </select>
          {voSessionData && <pre className="notice">{JSON.stringify(voSessionData, null, 2)}</pre>}
        </>
      )}

      {voSubTab === 'STT' && (
        <>
          <Button disabled={voBusy} onClick={runVoTestStt}>Record 2s and run STT test</Button>
          {voTestSttText && <pre className="notice">{JSON.stringify(voTestSttText, null, 2)}</pre>}
        </>
      )}

      {voSubTab === 'TTS' && (
        <>
          <textarea
            value={voTestTtsForm.text}
            onChange={(e) => setVoTestTtsForm({ text: e.target.value })}
            placeholder="Text to synthesize"
          />
          <Button disabled={voBusy || !voTestTtsForm.text} onClick={runVoTestTts}>Run TTS test</Button>
          {voTestTtsResult && <pre className="notice">{JSON.stringify(voTestTtsResult, null, 2)}</pre>}
        </>
      )}

      {voSubTab === 'Permissions' && (
        <div className="notice">
          microphone.capture: high sensitivity, explicit per-session consent required for public
          chat, real admin authorization required for the Admin Assistant. plugin.storage.local
          and chat.read.current are allow-by-default for voice sessions.
        </div>
      )}

      {voSubTab === 'Diagnostics' && (
        <>
          {voDiag && <pre className="notice">{JSON.stringify(voDiag, null, 2)}</pre>}
          {!voDiag && <Skeleton lines={2} />}
        </>
      )}

      {voSubTab === 'Metrics' && (
        <>
          {voMetrics && <pre className="notice">{JSON.stringify(voMetrics, null, 2)}</pre>}
          {!voMetrics && <div className="notice">No metrics yet.</div>}
        </>
      )}

      {voSubTab === 'Events' && (
        <ul className="notice">
          {voEventsList.map((e) => <li key={e.public_id}>{e.created_at} -- {e.event_type} -- {e.stage || 'n/a'} -- {e.message}</li>)}
          {!voEventsList.length && <li>No events yet.</li>}
        </ul>
      )}

      {voSubTab === 'Memory' && (
        <ul className="notice">
          {voMemoryList.map((m) => (
            <li key={m.public_id}>{m.created_at} -- {m.session_mode} -- final_status: {m.final_status} -- stt: {m.stt_backend_used || 'n/a'} -- tts: {m.tts_backend_used || 'n/a'} -- duration: {m.duration_ms ?? 'n/a'}ms</li>
          ))}
          {!voMemoryList.length && <li>No archived sessions yet.</li>}
        </ul>
      )}

      {voSubTab === 'Settings' && (
        <div className="notice">
          Max record seconds, max audio MB, and STT model size are configured via
          BRUD_VOICE_MAX_RECORD_SECONDS / BRUD_VOICE_MAX_AUDIO_MB / BRUD_VOICE_STT_MODEL_SIZE --
          see the Diagnostics sub-tab for the current effective values.
        </div>
      )}

      {voSubTab === 'History' && (
        <ul className="notice">
          {voMemoryList.map((m) => (
            <li key={m.public_id}>{m.created_at} -- session {m.session_id} -- {m.final_status}</li>
          ))}
          {!voMemoryList.length && <li>No history yet.</li>}
        </ul>
      )}
    </>
  )
}
