import { useEffect, useRef, useState } from 'react'
import { assessQuality, assessRecordQuality, createDatasetBuild, createDatasetExport, createDatasetRecord, createDatasetSource, datasetBuilds, datasetDuplicates, datasetRecords, datasetSources, datasetStatistics, datasetVersions, qualityIssues, qualitySummary, recordAction, recordReviews, runDatasetBuild, updateDatasetRecord, updateDatasetSource, validateDatasetBuild, verifyDatasetVersion } from '../services/api.js'
import ImportsPage from './ImportsPage.jsx'

const tabs = ['Overview', 'Sources', 'Records', 'Review Queue', 'Quality', 'Duplicates', 'Imports', 'Versions']
const emptyRecord = { source_public_id: '', record_type: 'instruction', language: 'ta', instruction: '', input_text: '', output_text: '', normalized_input: '', metadata: {} }

export default function DatasetsPage() {
  const [tab, setTab] = useState('Overview'), [data, setData] = useState(null), [sources, setSources] = useState([])
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [sourceForm, setSourceForm] = useState({ name: '', language: 'ta', licence_status: 'unknown', source_type: 'manual', metadata: {} })
  const [recordForm, setRecordForm] = useState(emptyRecord), [comments, setComments] = useState({})
  const [buildForm, setBuildForm] = useState({ dataset_name: 'brud_dataset', dataset_version: 'v0.1', minimum_quality_score: 0.8, require_ready_quality: false, split_configuration: { train_percent: 90, validation_percent: 5, test_percent: 5, seed: 42 }, selection_filters: {} })
  const [editingSource, setEditingSource] = useState(null), [editingRecord, setEditingRecord] = useState(null)
  const requestSequence = useRef(0)
  const activeTab = useRef(tab)
  async function load(active = tab) {
    const sequence = ++requestSequence.current
    setLoading(true); setError('')
    try {
      const sourcePage = await datasetSources()
      let nextData
      if (active === 'Overview') nextData = await datasetStatistics()
      else if (active === 'Sources') nextData = sourcePage
      else if (active === 'Records') nextData = await datasetRecords()
      else if (active === 'Review Queue') nextData = await datasetRecords('?status=pending_review')
      else if (active === 'Quality') nextData = { summary: await qualitySummary(), issues: await qualityIssues('?page_size=10'), records: await datasetRecords('?page_size=10') }
      else if (active === 'Duplicates') nextData = await datasetDuplicates()
      else if (active === 'Versions') nextData = { versions: await datasetVersions(), builds: await datasetBuilds() }
      else nextData = {}
      if (sequence === requestSequence.current) { setSources(sourcePage.items); setData(nextData) }
    } catch (reason) { if (sequence === requestSequence.current) setError(reason.message) } finally { if (sequence === requestSequence.current) setLoading(false) }
  }
  useEffect(() => { activeTab.current = tab; load(tab) }, [tab])
  async function saveSource(e) { e.preventDefault(); try { editingSource ? await updateDatasetSource(editingSource, sourceForm) : await createDatasetSource(sourceForm); setNotice(editingSource ? 'Source updated.' : 'Manual source created.'); setEditingSource(null); setSourceForm({ name: '', language: 'ta', licence_status: 'unknown', source_type: 'manual', metadata: {} }); load('Sources') } catch (reason) { setError(reason.message) } }
  async function saveRecord(e) { e.preventDefault(); try { editingRecord ? await updateDatasetRecord(editingRecord, recordForm) : await createDatasetRecord(recordForm); setNotice(editingRecord ? 'Record updated.' : 'Draft record created.'); setEditingRecord(null); setRecordForm(emptyRecord); load('Records') } catch (reason) { setError(reason.message) } }
  function editSource(source) { setEditingSource(source.public_id); setSourceForm({ name: source.name, language: source.language, licence_status: source.licence_status, source_type: source.source_type, metadata: source.metadata || {} }) }
  function editRecord(record) { setEditingRecord(record.public_id); setRecordForm({ source_public_id: record.source_public_id, record_type: record.record_type, language: record.language, instruction: record.instruction || '', input_text: record.input_text || '', output_text: record.output_text || '', normalized_input: record.normalized_input || '', metadata: record.metadata || {} }) }
  async function act(record, action, decision) { try { await recordAction(record.public_id, action, decision ? { decision, comments: comments[record.public_id] || null } : null); setNotice('Record updated.'); load(activeTab.current) } catch (reason) { setError(reason.message) } }
  async function assess(record) { try { await assessRecordQuality(record.public_id); setNotice('Quality assessment created.'); load(activeTab.current) } catch (reason) { setError(reason.message) } }
  async function bulkAssess() { try { const result = await assessQuality({ status: 'draft', max_records: 100 }); setNotice(`${result.assessed} record(s) assessed.`); load('Quality') } catch (reason) { setError(reason.message) } }
  async function createBuild(e) { e.preventDefault(); try { const build = await createDatasetBuild(buildForm); const preview = await validateDatasetBuild(build.public_id); setNotice(`Build preview: ${preview.selected_records} selected, ${preview.split_counts.train}/${preview.split_counts.validation}/${preview.split_counts.test} split.`); load('Versions') } catch (reason) { setError(reason.message) } }
  async function runBuild(build) { try { await runDatasetBuild(build.public_id, { confirm: true, allow_warnings: true }); setNotice('Dataset version finalized.'); load('Versions') } catch (reason) { setError(reason.message) } }
  async function verifyVersion(version) { try { const result = await verifyDatasetVersion(version.public_id); setNotice(result.verified ? 'Checksum verified.' : 'Checksum mismatch.'); } catch (reason) { setError(reason.message) } }
  async function exportVersion(version) { try { await createDatasetExport(version.public_id); setNotice('Dataset export created.'); load('Versions') } catch (reason) { setError(reason.message) } }
  async function history(record) { const result = await recordReviews(record.public_id); setNotice(`${result.items.length} review event(s) recorded.`) }
  return <><div className="dataset-tabs">{tabs.map((item) => <button className={tab === item ? 'active' : ''} onClick={() => { activeTab.current = item; setData(null); setTab(item) }} key={item}>{item}</button>)}</div>
    {notice && <div className="success-note" role="status">{notice}</div>}{error && <div className="form-error" role="alert">{error}</div>}
    {tab === 'Imports' ? <ImportsPage /> : loading || !data ? <div className="notice">Loading dataset workspace…</div> : <DatasetContent tab={tab} data={data} sources={sources} sourceForm={sourceForm} setSourceForm={setSourceForm} recordForm={recordForm} setRecordForm={setRecordForm} saveSource={saveSource} saveRecord={saveRecord} act={act} assess={assess} bulkAssess={bulkAssess} comments={comments} setComments={setComments} history={history} editingSource={editingSource} editingRecord={editingRecord} editSource={editSource} editRecord={editRecord} buildForm={buildForm} setBuildForm={setBuildForm} createBuild={createBuild} runBuild={runBuild} verifyVersion={verifyVersion} exportVersion={exportVersion} />}
  </>
}

function DatasetContent({ tab, data, sources, sourceForm, setSourceForm, recordForm, setRecordForm, saveSource, saveRecord, act, assess, bulkAssess, comments, setComments, history, editingSource, editingRecord, editSource, editRecord, buildForm, setBuildForm, createBuild, runBuild, verifyVersion, exportVersion }) {
  if (tab === 'Overview') return <><h2>Dataset overview</h2><section className="metric-grid">{Object.entries(data).filter(([,v]) => typeof v !== 'object').map(([k,v]) => <article className="status-card" key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v}</strong></article>)}</section><Distribution title="Status" data={data.by_status}/><Distribution title="Languages" data={data.by_language}/><Distribution title="Record types" data={data.by_record_type}/></>
  if (tab === 'Sources') return <><form className="inline-form" onSubmit={saveSource}><h2>{editingSource ? 'Edit source' : 'Create manual source'}</h2><label>Name<input value={sourceForm.name} onChange={(e)=>setSourceForm({...sourceForm,name:e.target.value})} required /></label><label>Language<select value={sourceForm.language} onChange={(e)=>setSourceForm({...sourceForm,language:e.target.value})}><option value="ta">Tamil</option><option value="en">English</option><option value="tgl">Tanglish</option><option value="mixed">Mixed</option></select></label><button>{editingSource ? 'Save source' : 'Create source'}</button></form><ItemList items={data.items} empty="No dataset sources yet." onEdit={editSource} /></>
  if (tab === 'Records') return <><form className="inline-form record-form" onSubmit={saveRecord}><h2>{editingRecord ? 'Edit dataset record' : 'Create dataset record'}</h2><label>Source<select value={recordForm.source_public_id} onChange={(e)=>setRecordForm({...recordForm,source_public_id:e.target.value})} required><option value="">Select source</option>{sources.map(s=><option key={s.public_id} value={s.public_id}>{s.name}</option>)}</select></label><label>Type<select value={recordForm.record_type} onChange={(e)=>setRecordForm({...recordForm,record_type:e.target.value})}>{['pretrain','instruction','chat','translation','tanglish_pair','safety','preference'].map(x=><option key={x}>{x}</option>)}</select></label><label>Language<select value={recordForm.language} onChange={(e)=>setRecordForm({...recordForm,language:e.target.value})}>{['ta','en','tgl','mixed'].map(x=><option key={x}>{x}</option>)}</select></label><label>Instruction<textarea value={recordForm.instruction} onChange={(e)=>setRecordForm({...recordForm,instruction:e.target.value})}/></label><label>Input<textarea value={recordForm.input_text} onChange={(e)=>setRecordForm({...recordForm,input_text:e.target.value})}/></label><label>Output<textarea value={recordForm.output_text} onChange={(e)=>setRecordForm({...recordForm,output_text:e.target.value})}/></label><button>{editingRecord ? 'Save record' : 'Create draft'}</button></form><RecordList items={data.items} act={act} assess={assess} history={history} editRecord={editRecord} /></>
  if (tab === 'Review Queue') return <><h2>Review queue</h2>{!data.items.length ? <div className="notice">No records are waiting for review.</div> : data.items.map(r=><article className="review-card" key={r.public_id}><strong>{r.instruction || r.record_type}</strong><p>{r.input_text}</p><p>{r.output_text}</p><label>Review comments<textarea value={comments[r.public_id]||''} onChange={e=>setComments({...comments,[r.public_id]:e.target.value})}/></label><div><button onClick={()=>assess(r)}>Assess</button><button onClick={()=>act(r,'review','approve')}>Approve</button><button onClick={()=>act(r,'review','reject')}>Reject</button><button onClick={()=>act(r,'review','request_changes')}>Request changes</button><button onClick={()=>history(r)}>History</button></div></article>)}</>
  if (tab === 'Quality') return <><h2>Dataset quality</h2><button onClick={bulkAssess}>Assess draft records</button><section className="metric-grid">{Object.entries(data.summary).filter(([,v]) => typeof v !== 'object').map(([k,v]) => <article className="status-card" key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v}</strong></article>)}</section><h3>Top issues</h3><ItemList items={data.summary.top_issue_codes.map((item) => ({ public_id: item.issue_code, name: item.issue_code, status: item.count }))} empty="No quality issues yet."/><h3>Recent issue details</h3><ItemList items={data.issues.items.map((item) => ({ public_id: item.public_id, name: item.issue_code, status: item.severity }))} empty="No assessed issue rows yet."/><h3>Records requiring action</h3><RecordList items={data.records.items} act={act} assess={assess} history={history} editRecord={editRecord}/></>
  if (tab === 'Versions') return <><h2>Dataset versions</h2><form className="inline-form" onSubmit={createBuild}><label>Name<input value={buildForm.dataset_name} onChange={(e)=>setBuildForm({...buildForm,dataset_name:e.target.value})}/></label><label>Version<input value={buildForm.dataset_version} onChange={(e)=>setBuildForm({...buildForm,dataset_version:e.target.value})}/></label><label>Minimum quality<input type="number" min="0" max="1" step="0.05" value={buildForm.minimum_quality_score} onChange={(e)=>setBuildForm({...buildForm,minimum_quality_score:Number(e.target.value)})}/></label><label><input type="checkbox" checked={buildForm.require_ready_quality} onChange={(e)=>setBuildForm({...buildForm,require_ready_quality:e.target.checked})}/> Require ready quality</label><button>Create build preview</button></form><h3>Build jobs</h3><div className="data-list">{data.builds.items.map((b)=><article key={b.public_id}><strong>{b.name}</strong><span>{b.status} · {b.selected_records} selected</span><button onClick={()=>runBuild(b)}>Run</button></article>)}</div><h3>Versions</h3><div className="data-list">{data.versions.items.map((v)=><article key={v.public_id}><strong>{v.name} {v.version}</strong><span>{v.status} · {v.record_count} records · {v.checksum_sha256}</span><button onClick={()=>verifyVersion(v)}>Verify</button><button onClick={()=>exportVersion(v)}>Export</button></article>)}</div></>
  return <><h2>Duplicate conflicts</h2><ItemList items={data.items} empty="No duplicate conflicts recorded." /></>
}
function Distribution({ title, data }) { return <><h3>{title}</h3><div className="distribution">{Object.entries(data).map(([k,v])=><span key={k}>{k}: <strong>{v}</strong></span>)}</div></> }
function ItemList({ items = [], empty, onEdit }) { return !items.length ? <div className="notice">{empty}</div> : <div className="data-list">{items.map((item)=><article key={item.public_id || item.created_at}><strong>{item.name || item.existing_record_public_id}</strong><span>{item.status || item.created_at}</span>{onEdit && <button onClick={()=>onEdit(item)}>Edit</button>}</article>)}</div> }
function RecordList({ items = [], act, assess, history, editRecord }) { return !items.length ? <div className="notice">No records yet.</div> : <div className="data-list">{items.map(r=><article key={r.public_id}><div><strong>{r.instruction || r.record_type}</strong><small>{r.language} · {r.status}</small></div><div>{assess&&<button onClick={()=>assess(r)}>Assess</button>}{['draft','pending_review'].includes(r.status)&&<button onClick={()=>editRecord(r)}>Edit</button>}{r.status==='draft'&&<button onClick={()=>act(r,'submit')}>Submit</button>}{r.status!=='archived'&&<button onClick={()=>act(r,'archive')}>Archive</button>}{r.status==='archived'&&<button onClick={()=>act(r,'restore')}>Restore</button>}<button onClick={()=>history(r)}>History</button></div></article>)}</div> }
