import { useEffect, useState } from 'react'
import { analyzeDocument, documentCandidateAction, documentCandidates, documentCapabilities, documentDetail, documentJobEvents, documentJobs, documentPage, documentPages, documents, downloadDocumentReport, editDocumentCandidate, editDocumentPage, importDocumentCandidates, processDocument, reprocessDocumentPage, segmentDocument, uploadDocument } from '../services/api.js'

const tabs = ['Overview', 'Upload', 'Processing', 'Page Review', 'Candidates']

export default function DocumentsPage() {
  const [tab, setTab] = useState('Overview'), [capabilities, setCapabilities] = useState(null), [items, setItems] = useState([])
  const [selected, setSelected] = useState(null), [pages, setPages] = useState([]), [page, setPage] = useState(null), [candidates, setCandidates] = useState([]), [jobs, setJobs] = useState([]), [events, setEvents] = useState([])
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [confirm, setConfirm] = useState(false)
  async function refresh() { setLoading(true); setError(''); try { const [ability, listing] = await Promise.all([documentCapabilities(), documents()]); setCapabilities(ability); setItems(listing.items) } catch (reason) { setError(reason.message) } finally { setLoading(false) } }
  useEffect(() => { refresh() }, [])
  async function open(document) { setBusy('details'); try { const [detail, pageList, candidateList, jobList] = await Promise.all([documentDetail(document.public_id), documentPages(document.public_id), documentCandidates(document.public_id), documentJobs(document.public_id)]); setSelected(detail); setPages(pageList.items); setCandidates(candidateList.items); setJobs(jobList.items); setTab('Processing'); if (jobList.items[0]) setEvents((await documentJobEvents(jobList.items[0].public_id)).items) } catch (reason) { setError(reason.message) } finally { setBusy('') } }
  async function action(label, callback) { setBusy(label); setError(''); try { await callback(); setNotice(`${label} completed.`); const detail = await documentDetail(selected.public_id); await open(detail) } catch (reason) { setError(reason.message) } finally { setBusy('') } }
  async function openPage(number) { try { setPage(await documentPage(selected.public_id, number)); setTab('Page Review') } catch (reason) { setError(reason.message) } }
  async function report() { try { const blob = await downloadDocumentReport(selected.public_id); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `brud-document-${selected.public_id}.csv`; anchor.click(); URL.revokeObjectURL(url); setNotice('Bounded document report created.') } catch (reason) { setError(reason.message) } }
  return <section className="documents-workspace"><header className="section-heading"><div><h2>Documents</h2><p>Secure local PDF extraction, page review, and draft candidate import.</p></div><button onClick={refresh}>Refresh</button></header>
    <div className="dataset-tabs">{tabs.map(value => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{value}</button>)}</div>
    {notice && <div className="success-note" role="status">{notice}</div>}{error && <div className="form-error" role="alert">{error}</div>}
    {tab === 'Upload' ? <DocumentUpload capabilities={capabilities} busy={busy} submit={async form => { setBusy('upload'); setError(''); try { const document = await uploadDocument(form); setNotice('PDF validated and registered.'); await refresh(); await open(document) } catch (reason) { setError(reason.message) } finally { setBusy('') } }} /> : loading ? <div className="notice">Loading document workspace…</div> : tab === 'Overview' ? <DocumentOverview items={items} capabilities={capabilities} open={open} /> : !selected ? <div className="notice">Open a document from Overview first.</div> : tab === 'Processing' ? <DocumentProcessing document={selected} pages={pages} jobs={jobs} events={events} busy={busy} analyze={() => action('Analysis', () => analyzeDocument(selected.public_id))} process={() => action('Extraction', () => processDocument(selected.public_id, { strategy: selected.extraction_strategy }))} openPage={openPage} report={report} /> : tab === 'Page Review' ? <PageReview page={page} pages={pages} busy={busy} openPage={openPage} save={text => action('Page edit', () => editDocumentPage(selected.public_id, page.page_number, { cleaned_text: text }))} reprocess={() => action('Page reprocessing', () => reprocessDocumentPage(selected.public_id, page.page_number, { strategy: 'auto' }))} /> : <CandidateReview document={selected} candidates={candidates} busy={busy} confirmed={confirm} setConfirmed={setConfirm} segment={() => action('Segmentation', () => segmentDocument(selected.public_id, { mode: 'paragraph_as_pretrain', language: selected.detected_language }))} edit={(id, body) => action('Candidate edit', () => editDocumentCandidate(selected.public_id, id, body))} choose={(id, choice) => action(`Candidate ${choice}`, () => documentCandidateAction(selected.public_id, id, choice))} importCandidates={() => action('Candidate import', () => importDocumentCandidates(selected.public_id))} />}
  </section>
}

function DocumentUpload({ capabilities, busy, submit }) {
  const [file, setFile] = useState(null), [strategy, setStrategy] = useState('auto'), [language, setLanguage] = useState('mixed')
  function send(event) { event.preventDefault(); const form = new FormData(); form.append('file', file); form.append('extraction_strategy', strategy); form.append('language', language); submit(form) }
  return <form className="document-upload" onSubmit={send}><h3>Upload PDF</h3><p>Maximum {Math.round((capabilities?.max_file_bytes || 0) / 1048576)} MB · {capabilities?.max_pages} pages · private local storage</p><label>PDF document<input type="file" accept="application/pdf,.pdf" onChange={event => setFile(event.target.files[0])} required /></label><label>Extraction strategy<select value={strategy} onChange={event => setStrategy(event.target.value)}><option value="auto">Automatic embedded/OCR</option><option value="embedded_text">Embedded text only</option><option value="ocr">OCR only</option><option value="hybrid">Hybrid</option></select></label><label>Preferred language<select value={language} onChange={event => setLanguage(event.target.value)}>{['ta','en','tgl','mixed','unknown'].map(value => <option key={value}>{value}</option>)}</select></label><div className={`capability ${capabilities?.ocr_available ? 'available' : 'unavailable'}`}><strong>{capabilities?.ocr_available ? 'OCR available' : 'OCR unavailable'}</strong><span>{capabilities?.ocr_languages?.join(', ') || 'Embedded extraction remains available'}</span></div><button disabled={Boolean(busy)}>{busy === 'upload' ? 'Uploading and validating…' : 'Upload securely'}</button>{busy === 'upload' && <progress aria-label="Document upload in progress" />}</form>
}

function DocumentOverview({ items, capabilities, open }) {
  const counts = Object.fromEntries(['processing','review_ready','completed','failed'].map(status => [status, items.filter(item => item.status === status).length]))
  return <><section className="metric-grid"><article className="status-card"><span>Total documents</span><strong>{items.length}</strong></article>{Object.entries(counts).map(([key,value]) => <article className="status-card" key={key}><span>{key.replace('_',' ')}</span><strong>{value}</strong></article>)}<article className="status-card"><span>OCR capability</span><strong>{capabilities?.ocr_available ? 'Tamil + English ready' : 'Unavailable'}</strong></article></section><h3>Document history</h3>{!items.length ? <div className="notice">No documents uploaded yet.</div> : <div className="document-list">{items.map(item => <button key={item.public_id} onClick={() => open(item)}><strong>{item.original_filename}</strong><span>{item.page_count} pages · {item.status}</span><span>{item.extraction_strategy} · {item.checksum_prefix}</span></button>)}</div>}</>
}

function DocumentProcessing({ document, pages, jobs, events, busy, analyze, process, openPage, report }) {
  return <section className="document-detail"><header><div><h3>{document.original_filename}</h3><p>{document.file_size_bytes} bytes · {document.page_count} pages · {document.status}</p></div><span className="checksum">SHA-256 {document.checksum_prefix}</span></header><div className="document-actions"><button disabled={Boolean(busy)} onClick={analyze}>Analyze pages</button><button disabled={Boolean(busy)} onClick={process}>Process {document.extraction_strategy}</button><button onClick={report}>Download report</button></div><h4>Pages</h4><div className="page-grid">{pages.map(item => <button key={item.public_id} onClick={() => openPage(item.page_number)}><strong>Page {item.page_number}</strong><span>{item.extraction_method} · {item.extraction_status}</span><small>{item.text_length} characters · {item.warnings?.length || 0} warnings</small></button>)}</div><h4>Job history</h4>{!jobs.length ? <div className="notice">No processing jobs.</div> : <ol>{jobs.map(job => <li key={job.public_id}>{job.job_type} · {job.status} · {Math.round(job.progress * 100)}%</li>)}</ol>}<h4>Latest events</h4>{!events.length ? <div className="notice">No events for the latest job.</div> : <ol>{events.map((item,index) => <li key={`${item.created_at}-${index}`}>{item.event_type}{item.page_number ? ` · page ${item.page_number}` : ''}</li>)}</ol>}</section>
}

function PageReview({ page, pages, busy, openPage, save, reprocess }) {
  const [text, setText] = useState(page?.cleaned_text || '')
  useEffect(() => setText(page?.cleaned_text || ''), [page])
  if (!page) return <div className="notice">Select a page from Processing.</div>
  const index = pages.findIndex(item => item.page_number === page.page_number)
  return <section className="page-review"><header><div><h3>Page {page.page_number}</h3><p>{page.extraction_method} · {page.extraction_status} · {page.text_length} characters {page.confidence_score != null ? `· ${Math.round(page.confidence_score * 100)}% confidence` : ''}</p></div><div><button disabled={index <= 0} onClick={() => openPage(pages[index - 1].page_number)}>Previous</button><button disabled={index >= pages.length - 1} onClick={() => openPage(pages[index + 1].page_number)}>Next</button></div></header>{page.warnings?.map(item => <p className="row-warning" key={item.code}>{item.code}: {item.message}</p>)}<details><summary>Raw extraction evidence</summary><pre>{page.raw_text || 'No raw text extracted.'}</pre></details><label>Cleaned text editor<textarea value={text} onChange={event => setText(event.target.value)} rows="16" /></label><div><button disabled={Boolean(busy) || text === page.cleaned_text} onClick={() => save(text)}>Save cleaned text</button><button disabled={Boolean(busy)} onClick={reprocess}>Reprocess page</button></div>{text !== page.cleaned_text && <p className="unsaved-note">Unsaved page edits</p>}</section>
}

function CandidateReview({ document, candidates, busy, confirmed, setConfirmed, segment, edit, choose, importCandidates }) {
  const selected = candidates.filter(item => item.status === 'selected').length
  return <section className="candidate-review"><header className="section-heading"><div><h3>Candidate records</h3><p>Deterministic pretrain segments preserve page provenance and import as drafts only.</p></div><button disabled={Boolean(busy)} onClick={segment}>Generate candidates</button></header>{!candidates.length ? <div className="notice">No candidates yet. Review pages, then generate candidates.</div> : <div className="candidate-list">{candidates.map(item => <CandidateCard key={item.public_id} item={item} edit={edit} choose={choose} busy={busy} />)}</div>}<div className="confirmation-box"><strong>Draft import confirmation</strong><p>{selected} selected · {candidates.filter(item => item.status === 'duplicate').length} duplicates · document {document.original_filename}</p><label><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} /> I reviewed the candidates and confirm draft-only dataset import.</label><button disabled={!confirmed || !selected || Boolean(busy)} onClick={importCandidates}>Import selected candidates</button></div></section>
}

function CandidateCard({ item, edit, choose, busy }) {
  const [text, setText] = useState(item.output_text || item.candidate_text || '')
  return <article><header><strong>Candidate {item.sequence_number} · pages {item.source_page_start}–{item.source_page_end}</strong><span>{item.status} · {item.language}</span></header><textarea aria-label={`Candidate ${item.sequence_number} text`} value={text} onChange={event => setText(event.target.value)} rows="5" /><div><button disabled={Boolean(busy) || text === (item.output_text || item.candidate_text || '')} onClick={() => edit(item.public_id, { output_text: text, candidate_text: text })}>Save edit</button><button disabled={Boolean(busy) || !['valid','warning','draft'].includes(item.status)} onClick={() => choose(item.public_id, 'select')}>Select</button><button disabled={Boolean(busy) || item.status === 'imported'} onClick={() => choose(item.public_id, 'reject')}>Reject</button></div>{item.duplicate_record_public_id && <p className="row-warning">Duplicate of record {item.duplicate_record_public_id}</p>}</article>
}
