import { useEffect, useState } from 'react'
import { cancelImport, confirmImport, downloadImportReport, importEvents, importJobs, importRows, parseImport, updateImportMapping, uploadImport } from '../services/api.js'

const presets = {
  'instruction,input,output': { instruction: 'instruction', input_text: 'input', output_text: 'output' },
  'question,answer': { instruction: 'question', output_text: 'answer' },
  'tanglish,tamil,response': { input_text: 'tanglish', normalized_input: 'tamil', output_text: 'response' },
  'source,target': { input_text: 'source', output_text: 'target' },
  text: { output_text: 'text' },
}

export default function ImportsPage() {
  const [jobs, setJobs] = useState([]), [selected, setSelected] = useState(null), [rows, setRows] = useState([]), [events, setEvents] = useState([])
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [rowTab, setRowTab] = useState(''), [confirmed, setConfirmed] = useState(false)
  const [form, setForm] = useState({ file: null, record_type: 'instruction', language: 'ta', mode: 'skip_duplicates', preset: 'instruction,input,output', txt_mode: 'one_record_per_line', delimiter: 'comma' })
  async function refresh() { setLoading(true); try { setJobs((await importJobs()).items) } catch (reason) { setError(reason.message) } finally { setLoading(false) } }
  useEffect(() => { refresh() }, [])
  async function open(job, status = rowTab) { setBusy('details'); setError(''); try { const [page, history] = await Promise.all([importRows(job.public_id, status ? `?status=${status}&page_size=50` : '?page_size=50'), importEvents(job.public_id)]); setSelected(job); setRows(page.items); setEvents(history.items) } catch (reason) { setError(reason.message) } finally { setBusy('') } }
  async function upload(event) { event.preventDefault(); if (!form.file) return setError('Choose a dataset file.'); setBusy('upload'); setError(''); try { const body = new FormData(); body.append('file', form.file); body.append('record_type', form.record_type); body.append('default_language', form.language); body.append('import_mode', form.mode); body.append('field_mapping_json', JSON.stringify(presets[form.preset])); body.append('parser_options_json', JSON.stringify({ txt_mode: form.txt_mode, delimiter: form.delimiter })); const job = await uploadImport(body); setNotice('Upload registered. Review mapping, then parse.'); await refresh(); setSelected(job); setRows([]); setEvents([]) } catch (reason) { setError(reason.message) } finally { setBusy('') } }
  async function action(name, callback) { setBusy(name); setError(''); try { const job = await callback(); setSelected(job); setNotice(`${name} completed.`); await refresh(); await open(job) } catch (reason) { setError(reason.message) } finally { setBusy('') } }
  async function saveMapping() { return updateImportMapping(selected.public_id, { field_mapping: presets[form.preset], record_type: form.record_type, default_language: form.language, import_mode: form.mode, parser_options: { txt_mode: form.txt_mode, delimiter: form.delimiter } }) }
  async function report() { try { const blob = await downloadImportReport(selected.public_id); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `brud-import-${selected.public_id}.csv`; anchor.click(); URL.revokeObjectURL(url); setNotice('Bounded error report created.') } catch (reason) { setError(reason.message) } }
  return <section className="imports-workspace"><header className="section-heading"><div><h2>Dataset imports</h2><p>Preview, validate, and confirm bounded local files.</p></div><button onClick={refresh}>Refresh</button></header>
    {notice && <div className="success-note" role="status">{notice}</div>}{error && <div className="form-error" role="alert">{error}</div>}
    <form className="import-upload" onSubmit={upload}><h3>Upload dataset</h3><p>.json, .jsonl, .csv, .txt · maximum 10 MB</p><label>Dataset file<input type="file" accept=".json,.jsonl,.csv,.txt" onChange={event => setForm({ ...form, file: event.target.files[0] })} required /></label><label>Record type<select value={form.record_type} onChange={event => setForm({ ...form, record_type: event.target.value })}>{['pretrain','instruction','chat','translation','tanglish_pair','safety','preference'].map(value => <option key={value}>{value}</option>)}</select></label><label>Default language<select value={form.language} onChange={event => setForm({ ...form, language: event.target.value })}>{['ta','en','tgl','mixed','unknown'].map(value => <option key={value}>{value}</option>)}</select></label><label>Mapping preset<select value={form.preset} onChange={event => setForm({ ...form, preset: event.target.value })}>{Object.keys(presets).map(value => <option key={value}>{value}</option>)}</select></label><label>Import mode<select value={form.mode} onChange={event => setForm({ ...form, mode: event.target.value })}><option value="create_only">Create only</option><option value="skip_duplicates">Skip duplicates</option></select></label><label>TXT mode<select value={form.txt_mode} onChange={event => setForm({ ...form, txt_mode: event.target.value })}><option value="one_record_per_line">One record per line</option><option value="whole_file_as_pretrain">Whole file as pretrain</option></select></label><label>CSV delimiter<select value={form.delimiter} onChange={event => setForm({ ...form, delimiter: event.target.value })}><option value="comma">Comma</option><option value="semicolon">Semicolon</option><option value="tab">Tab</option></select></label><button disabled={Boolean(busy)}>{busy === 'upload' ? 'Uploading…' : 'Upload securely'}</button>{busy === 'upload' && <progress aria-label="Upload in progress" />}</form>
    <h3>Import history</h3>{loading ? <div className="notice">Loading imports…</div> : !jobs.length ? <div className="notice">No import jobs yet.</div> : <div className="import-list">{jobs.map(job => <button className="import-row" key={job.public_id} onClick={() => open(job)}><strong>{job.original_filename}</strong><span>{job.detected_file_type} · {job.status}</span><span>{job.total_rows} rows · {job.imported_rows} imported</span></button>)}</div>}
    {selected && <ImportDetails job={selected} form={form} setForm={setForm} saveMapping={() => action('Mapping update', saveMapping)} parse={() => action('Parse', () => parseImport(selected.public_id))} cancel={() => action('Cancellation', () => cancelImport(selected.public_id))} confirm={() => action('Import', () => confirmImport(selected.public_id, { confirm: true, include_warnings: true }))} confirmed={confirmed} setConfirmed={setConfirmed} report={report} rowTab={rowTab} setRowTab={async value => { setRowTab(value); await open(selected, value) }} rows={rows} events={events} busy={busy} />}
  </section>
}

function ImportDetails({ job, form, setForm, saveMapping, parse, cancel, confirm, confirmed, setConfirmed, report, rowTab, setRowTab, rows, events, busy }) {
  const counts = ['total_rows','valid_rows','warning_rows','duplicate_rows','invalid_rows','imported_rows','failed_rows']
  return <section className="import-details"><h3>{job.original_filename}</h3><p>{job.detected_file_type} · {job.file_size_bytes} bytes · {job.encoding} · {job.status}</p><div className="import-counts">{counts.map(key => <span key={key}>{key.replaceAll('_',' ')} <strong>{job[key]}</strong></span>)}</div>
    {job.available_actions?.parse && <fieldset><legend>Field mapping</legend><p>Selected source fields: {Object.values(job.field_mapping || {}).join(', ') || 'Choose a mapping preset'}</p><label>Preset<select value={form.preset} onChange={event => setForm({ ...form, preset: event.target.value })}>{Object.keys(presets).map(value => <option key={value}>{value}</option>)}</select></label><pre>{JSON.stringify(presets[form.preset], null, 2)}</pre><button onClick={saveMapping} disabled={Boolean(busy)}>Save mapping</button><button onClick={parse} disabled={Boolean(busy)}>Parse and preview</button></fieldset>}
    {job.status === 'preview_ready' && <div className="confirmation-box"><strong>Confirmation summary</strong><p>{job.valid_rows + job.warning_rows} eligible · {job.duplicate_rows} duplicates · {job.invalid_rows} invalid · mode: {job.import_mode}</p><label><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} /> I reviewed the preview and explicitly confirm this import.</label><button disabled={!confirmed || Boolean(busy)} onClick={confirm}>Confirm import</button></div>}
    <div className="preview-tabs">{['','valid','warning','duplicate','invalid','imported','skipped'].map(value => <button className={rowTab === value ? 'active' : ''} onClick={() => setRowTab(value)} key={value}>{value || 'All'}</button>)}</div>
    {!rows.length ? <div className="notice">No preview rows for this selection.</div> : <div className="preview-list">{rows.map(row => <article key={row.public_id}><strong>Row {row.row_number} · {row.row_status}</strong><span>{row.record_type} · {row.language}</span><details><summary>Original and normalized preview</summary><pre>{JSON.stringify(row.raw_data, null, 2)}</pre><pre>{JSON.stringify(row.normalized_data, null, 2)}</pre></details>{row.validation_errors?.map(error => <p className="row-error" key={error.code}>{error.code}: {error.message}</p>)}{row.validation_warnings?.map(warning => <p className="row-warning" key={`${warning.code}-${warning.field}`}>{warning.code}: {warning.message}</p>)}</article>)}</div>}
    <div className="import-actions"><button onClick={report}>Error report</button>{job.available_actions?.cancel && <button onClick={cancel}>Cancel job</button>}</div><h4>Import events</h4>{!events.length ? <div className="notice">No events yet.</div> : <ol>{events.map((event, index) => <li key={`${event.created_at}-${index}`}>{event.event_type} · {event.created_at}</li>)}</ol>}
  </section>
}
