import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import MiniBrainPage from './MiniBrainPage.jsx'

// Phase 4A safety net: this file previously had zero test coverage (36
// tabs, 424 useState calls, 162 handlers). Every function MiniBrainPage.jsx
// imports from services/api.js is mocked here so any tab can be mounted
// without a real backend; most default to `{ items: [], total: 0 }` --
// deliberately minimal, but matching this file's dominant list-endpoint
// shape (confirmed by reading several load*() handlers, e.g.
// `setViSessionsList(sessions.items)` with no `?.`/`?? []` fallback) so
// `.items.map()` doesn't throw. A handful of functions are overridden with
// a more specific shape for fields the component reads unconditionally,
// without optional chaining (found by reading the source, not guessed).
vi.mock('../services/api.js', () => ({
  analyzeQuestion: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  capabilityDiagnostics: vi.fn(() => Promise.resolve({ ai_model_used: false, max_retries: 0, known_profiles: [] })),
  capabilityGenerate: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningAnalyzeDifficulty: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningAnalyzeFailures: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningAnalyzeHallucinations: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningAnalyzeKnowledgeGaps: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningCollectFeedback: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningDetectWeakTopics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningDiagnostics: vi.fn(() => Promise.resolve({ pipeline_stages: [], writes_scope: 'none' })),
  continuousLearningEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningRankPriorities: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningRecommendDatasets: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningRecommendTraining: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  continuousLearningSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcBuildDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcBuildLearningQueue: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcBuildRoadmap: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcEvolveKnowledgeGaps: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcGenerateRecommendation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcIngestProviderResults: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcListMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcPlanDatasetEvolution: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcPrepareProviderRequest: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcRecordMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  clcSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  datasetAdvancedDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  datasetAdvancedReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  datasetIntelligenceDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  datasetIntelligenceReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  disableMiniBrain: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  enableMiniBrain: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  knowledgeCoreCoverage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  knowledgeCoreDomains: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  knowledgeCoreItem: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorAnalyzeTraining: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorCompareModels: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorDecideDataset: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorDecideRag: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorFinalizeRag: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorMonitorTraining: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorProfiles: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorRecommendations: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorReleaseCandidate: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorRunBenchmark: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorRunRag: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorSubmitTraining: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  learningSupervisorValidateDataset: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  listRuntimeModels: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  loadRuntimeModel: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  miniBrainDiagnostics: vi.fn(() => Promise.resolve({ config_issues: [], event_count: 0, runtime_backend: 'local', model_integrated: false })),
  miniBrainHealth: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  miniBrainLogs: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  miniBrainRuntimeHealth: vi.fn(() => Promise.resolve({
    backend_type: 'local', model_loaded: false, model_id: null, benchmark_rating: null,
    tokens_per_second: null, available_ram_gb: 0, external_provider_enabled: false,
    external_provider_name: null, tamil_quality_status: 'good', english_quality_status: 'good',
    next_action: { en: 'No action needed.', ta: 'எந்த நடவடிக்கையும் தேவையில்லை.' },
  })),
  miniBrainSettings: vi.fn(() => Promise.resolve({ config: { log_level: 'info', runtime_backend: 'local' } })),
  miniBrainStatus: vi.fn(() => Promise.resolve({ enabled: true, runtime_status: 'running', health: { status: 'healthy' } })),
  miniBrainVersion: vi.fn(() => Promise.resolve({ module_version: '1.0.0', phase: 'MB-01' })),
  qualityDiagnostics: vi.fn(() => Promise.resolve({ ai_model_used: false, database_tables: 0, pipeline_stages: [] })),
  qualityGenerate: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  miniBrainDefaultRetrievalProfile: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  sendMiniBrainGroundedMessage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  registerRuntimeModel: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineActivate: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineConvert: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineCreateVersion: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineDiagnostics: vi.fn(() => Promise.resolve({ quantization_levels_supported: [] })),
  releasePipelineEvaluateRollback: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineExecuteRollback: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelinePerformance: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineQuantize: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineRegistry: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineValidateCheckpoint: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  releasePipelineVerify: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcAddProvider: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcAdminReviewDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcAdminReviewRag: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcAnalyzeTrainingReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcBuildDatasetDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcBuildLocalDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcCheckTrainingGate: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcFinalizeRagEvaluation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcIngestProviderResults: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcListMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcListProviders: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcPrepareProviderRequestPackage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcPrepareResearchRequest: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcRecordMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcRunRagEvaluation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcSelectMode: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rcSetProviderStatus: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deAdminReviewRag: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deFinalizeRagEvaluation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deGenerateRecommendation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deRunDatasetEvolution: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deRunKnowledgeEvolution: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deRunRagEvaluation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deRunSimulation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  deSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcAdminDecide: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcGenerateRecommendation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcGenerateTimeline: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcGenerateTrainingReadiness: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcLinkDatasetEvolution: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcLinkResearch: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcLinkResearchCenter: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcLinkTraining: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcPredictImprovement: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcRefreshResearchCenter: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcRefreshTraining: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcRunRagFirstEnforcement: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunDatasetDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunGrammarAnalysis: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunLanguageScan: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunOcrAnalysis: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunQualityScore: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunSpellAnalysis: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunTanglishAnalysis: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunTranslationAnalysis: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liRunUnicodeValidation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  liSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viAnnotate: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viFinishAnnotation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viImages: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viObjects: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunBoundingBoxPlan: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunCaption: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunDatasetDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunImageExtraction: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunImageQuality: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunKnowledgeGraph: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunOcrCrossValidation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunQaGeneration: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunQualityScore: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viRunVisionUnderstanding: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  viSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmCorrections: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmFinishReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmLearningMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmPredictions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmProviders: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmReviewPrediction: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunCaption: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunCorrectionMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunDatasetDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunImageLoad: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunKnowledgeGraph: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunObjectDetection: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunOcrCrossValidation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunProviderSelection: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunQualityScore: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunRelationshipDetection: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmRunSceneDetection: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vmSetProviderStatus: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdDatasetMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdDeleteDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdExportDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdMergeDatasets: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRecords: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunCollectImages: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunCollectSources: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunCollectText: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunConversationBuilder: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunDatasetDraft: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunDuplicateDetection: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunInstructionBuilder: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunMergeMetadata: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdRunQualityAnalysis: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  mdSplitDataset: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrCorrect: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrEvidence: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRagMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunAnswer: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunEvidenceFusion: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunHallucinationCheck: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunImageRetrieval: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunKnowledgeGraphRetrieval: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunObjectRetrieval: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunOcrRetrieval: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunQuality: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrRunTextRetrieval: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  vrSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpPackages: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRagMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunAnalyzeLanguage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunAnalyzeTokenizer: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunAnalyzeVision: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunBuildPackage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunCollectDatasets: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunCollectRagMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunEstimateHardware: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunPlanCurriculum: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpRunPlanSplits: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tpSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecExports: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecResults: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunCollectDatasets: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunCollectRagSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunCollectTrainingPackages: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunGroundingRetrievalBenchmarks: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunLanguageBenchmarks: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunMultimodalBenchmarks: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunOcrBenchmarks: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunPackageBenchmarks: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecRunRegression: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  ecSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgArtifacts: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgBuildPackage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgBuildRiskRollback: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgRunBenchmarks: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgRunCollectDatasets: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgRunCollectEvaluation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgRunCollectPackage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgRunCollectRag: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgRunCompliance: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgRunSafety: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rgSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaAdminReview: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaAnalyze: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaArchive: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaAuthorize: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaBuildEvidence: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaCollect: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaDispatch: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaNormalize: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaProviderRuns: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaSanitize: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaSelectProviders: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  gaSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teArchive: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teAudit: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teAuthorize: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teBuildManifest: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teCancel: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teCheckpoints: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teCreateJob: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teFinalize: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teJob: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teJobs: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teMetrics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tePause: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  tePlanResources: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teReserveRuntime: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teResume: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teSaveCheckpoint: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teStart: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teStreamMetric: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teValidatePackage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  teValidateRelease: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrAnalytics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrCandidate: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrCandidateEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrCandidates: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrClusters: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrExportAnalytics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrExportCandidates: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrGenerateCandidates: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrMessages: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrReviewCandidate: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrSessionEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pcrSignals: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgArchivePlugin: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgBuildFilesystemPolicy: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgBuildNetworkPolicy: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgBuildSandboxProfile: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgCheckPolicy: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgClassifyCapabilities: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgComputeRiskScore: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgConsents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgDisablePlugin: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgEnablePlugin: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgEvaluatePermission: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgGrantPermission: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgIssueToken: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgPermissions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgPlugin: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgPlugins: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgRegisterPlugin: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgRequestConsent: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgRevokePermission: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgRuntimeEvent: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  pgValidateManifest: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prArchiveExecution: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prCancelExecution: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prExecute: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prExecution: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prExecutionLogs: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prExecutions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prGenerateReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prPublicExecute: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prRuntimeEvent: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  prStatistics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  reloadRuntimeModel: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  runKnowledgeCoreValidation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  runtimeDiagnostics: vi.fn(() => Promise.resolve({
    registered_model_count: 0,
    statistics: { total_generations: 0, memory_measurement: 'unavailable' },
    health: { status: 'healthy' },
  })),
  runtimeStatistics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  runtimeStatus: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  searchKnowledgeCore: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  seedKnowledgeCore: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  unloadRuntimeModel: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  updateMiniBrainSettings: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voStatistics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voTestStt: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voTestTts: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voPublicCreateSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voPublicFinishSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  voPublicSendChunk: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psDiagnostics: vi.fn(() => Promise.resolve({
    encryption_available: false, configured_provider_count: 0, enabled_provider_count: 0,
    unavailable_providers: [], missing_encryption_key: false,
  })),
  psProviders: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psCreateProvider: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psUpdateProvider: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psEnableProvider: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psDisableProvider: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psSetSecret: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psDeleteSecret: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psTestConnection: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psProviderAudit: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psArchiveProvider: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  psMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrSessions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrMessages: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrDeleteSession: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrChat: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrExplainPage: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrSummarizeReport: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrSummarizeRegression: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrExplainError: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lrNextActions: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lcHardware: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lcScanModels: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lcRecommendations: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lcSaveLocalModel: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lcSaveProvider: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lcProvidersCatalog: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lcSetupGuide: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  lcDiagnostics: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmHardware: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmCatalog: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmInstalled: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmStatus: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmRecommendation: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmDownload: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmVerify: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmInstall: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmLoad: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmUnload: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmBenchmark: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmRemove: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmEvents: vi.fn(() => Promise.resolve({ items: [], total: 0 })),
  rmMemory: vi.fn(() => Promise.resolve({ items: [], total: 0 })),}))

const api = await import('../services/api.js')

// Mirrors the real `tabs` array in MiniBrainPage.jsx:111-119 -- duplicated
// here (not imported) since the component doesn't export it.
const TABS = [
  'Overview', 'Settings', 'Logs', 'Diagnostics', 'Knowledge Core', 'Intelligence Engine', 'Runtime',
  'Response Quality', 'Capability', 'Dataset Intelligence', 'Learning Supervisor', 'Release Pipeline',
  'Continuous Learning', 'Continuous Learning Center', 'Research Center', 'Dataset Evolution',
  'Pipeline Coordinator', 'Language Intelligence', 'Vision Intelligence', 'Vision Model Center',
  'Multimodal Dataset Generator', 'Vision RAG', 'Training Pipeline', 'Evaluation Center',
  'Release Governance', 'External AI Gateway', 'Training Engine', 'Public Chat Runtime',
  'Plugin Governance', 'Plugin Runtime', 'Voice Runtime', 'Provider Settings', 'Assistant Intelligence',
  'Local Setup', 'Runtime Manager', 'Future Model',
]

beforeEach(() => {
  window.location.hash = ''
})

afterEach(() => {
  vi.clearAllMocks()
})

describe('MiniBrainPage', () => {
  describe('tab switching (smoke test across all 36 real top-level tabs)', () => {
    it.each(TABS)('opens the "%s" tab without throwing or showing a generic crash banner', async (tabName) => {
      const user = userEvent.setup()
      render(<MiniBrainPage />)
      await screen.findByRole('heading', { name: 'Brud Mini Brain' })
      const button = screen.getByRole('button', { name: tabName })
      await user.click(button)
      await waitFor(() => expect(button).toHaveClass('active'))
      expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    })
  })

  describe('initialTab deep-link (Admin Assistant widget -> "Open Mini Brain Assistant")', () => {
    it('opens the tab requested via the initialTab prop', async () => {
      render(<MiniBrainPage initialTab="Assistant Intelligence" />)
      await waitFor(() => expect(screen.getByRole('button', { name: 'Assistant Intelligence' })).toHaveClass('active'))
    })
  })

  describe('top-level tab hash persistence (mirrors ProductionReadinessPage.jsx)', () => {
    it('switching tabs updates window.location.hash', async () => {
      const user = userEvent.setup()
      render(<MiniBrainPage />)
      await screen.findByRole('heading', { name: 'Brud Mini Brain' })
      await user.click(screen.getByRole('button', { name: 'Logs' }))
      await waitFor(() => expect(window.location.hash).toContain('tab=Logs'))
    })

    it('mounting with a valid hash opens that tab', async () => {
      window.location.hash = '#Brud%20Mini%20Brain?tab=Runtime'
      render(<MiniBrainPage />)
      await waitFor(() => expect(screen.getByRole('button', { name: 'Runtime' })).toHaveClass('active'))
    })

    it('an invalid hash falls back to Overview', async () => {
      window.location.hash = '#Brud%20Mini%20Brain?tab=NotARealTab'
      render(<MiniBrainPage />)
      await waitFor(() => expect(screen.getByRole('button', { name: 'Overview' })).toHaveClass('active'))
    })
  })

  // Step 3A replaces this panel's body with <ChatPanel variant="compact" />.
  // Written now as the target spec for that step.
  describe.skip('Grounded Chat Test (MB-37) panel (Step 3A)', () => {
    it('sends through the real ChatPanel and renders a reply', async () => {})
  })

  // Step 3B replaces the Chat sub-tab with <ChatPanel variant="full" />.
  // Written now as the target spec for that step.
  describe.skip('Assistant Intelligence -> Chat sub-tab (Step 3B)', () => {
    it('sends through the real ChatPanel and renders a reply', async () => {})
  })

  describe('a representative logic-untouched tab (Vision Intelligence): load -> error -> retry -> success', () => {
    it('shows the real error banner on failure, then recovers once the retry succeeds', async () => {
      const user = userEvent.setup()
      api.viSessions.mockRejectedValueOnce(new Error('Vision Intelligence unavailable.'))
      render(<MiniBrainPage />)
      await screen.findByRole('heading', { name: 'Brud Mini Brain' })

      await user.click(screen.getByRole('button', { name: 'Vision Intelligence' }))
      expect(await screen.findByText('Vision Intelligence unavailable.')).toBeInTheDocument()

      // Step 2a's ErrorBanner gives this a real Retry control, wired to
      // re-select (and so re-load) the currently active tab.
      await user.click(screen.getByRole('button', { name: 'Retry' }))
      await waitFor(() => expect(screen.queryByText('Vision Intelligence unavailable.')).not.toBeInTheDocument())
      expect(screen.getByText(/MB-14 -- Vision Intelligence/)).toBeInTheDocument()
    })
  })
})
