"""MB-26: real end-to-end smoke test using a genuine, well-formed tiny
WAV audio fixture (not arbitrary bytes) driven through a real
`create_app()`-booted application, MockSpeechBackend, and
MockTtsBackend.

Explicitly proves every claim in the phase spec's own "Real smoke
test" section:
  - audio accepted
  - transcript produced by MockSpeechBackend
  - response generated through PublicChatRoutingService
  - TTS file generated by MockTtsBackend
  - session archived (closed, status=completed)
  - no raw audio stored in the database
  - MB-24 plugin state unchanged

This is a committed pytest module (this project's actual convention
for regression-suite membership), not a standalone script -- see the
MB-26 completion report's Deviations section for why.
"""

from __future__ import annotations

import io
import sqlite3
import struct
import wave
from pathlib import Path

import pytest

from backend.core.config import Settings
from backend.database.migrations import initialize_database
from backend.services.mini_brain_voice_runtime_service import MiniBrainVoiceRuntimeService


def _build_tiny_wav_fixture() -> bytes:
    """A genuine, well-formed 16-bit mono PCM WAV file: a short,
    deterministic sine-ish waveform, not just arbitrary bytes wearing a
    .wav extension."""
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(16_000)
        samples = [int(200 * ((i % 100) - 50)) for i in range(1600)]  # 0.1s of a simple wave, within int16 range
        wav_file.writeframes(struct.pack(f"<{len(samples)}h", *samples))
    return buffer.getvalue()


@pytest.fixture
def settings(tmp_path: Path) -> Settings:
    result = Settings(
        database_path=tmp_path / "api.db", database_backup_dir=tmp_path / "backups",
        allowed_data_dir=tmp_path, voice_audio_dir=tmp_path / "voice_audio",
        document_dir=tmp_path / "documents", document_report_dir=tmp_path / "documents" / "reports",
        allow_external_storage=True, log_level="CRITICAL", public_chat_model_enabled=True,
    )
    initialize_database(result.resolved_database_path)
    return result


def test_real_wav_fixture_is_well_formed() -> None:
    """Sanity-checks the fixture itself is a genuine, parseable WAV
    file before using it -- proves this isn't just arbitrary bytes."""
    wav_bytes = _build_tiny_wav_fixture()
    with wave.open(io.BytesIO(wav_bytes), "rb") as wav_file:
        assert wav_file.getnchannels() == 1
        assert wav_file.getsampwidth() == 2
        assert wav_file.getframerate() == 16_000
        assert wav_file.getnframes() == 1600


def test_full_voice_smoke_end_to_end(settings: Settings) -> None:
    from backend.main import create_app

    app = create_app(settings)
    assert app is not None  # a real create_app() boot, not a bare service instantiation

    wav_bytes = _build_tiny_wav_fixture()
    svc = MiniBrainVoiceRuntimeService(settings)

    # -- diagnostics honestly report mock backends in this environment --------------
    diagnostics = svc.diagnostics()
    assert diagnostics["stt_available"] is False
    assert diagnostics["stt_backend"] == "mock"
    assert diagnostics["tts_available"] is False
    assert diagnostics["tts_backend"] == "mock"
    assert diagnostics["wakeword_enabled"] is False
    assert diagnostics["local_only"] is True
    assert diagnostics["gpu_required"] is False

    # -- stage 1: create session --------------------------------------------------
    session = svc.create_voice_session(session_mode="public_chat", raw_client_key="192.0.2.100")
    sid = session["public_id"]
    assert session["stage"] == "created"

    # -- stage 2: check microphone permission (explicit consent given) -------------
    session = svc.run_check_microphone_permission_stage(sid, explicit_consent_given=True)
    assert session["status"] == "active"
    assert session["stage"] == "permission_checked"

    # -- stage 3: validate voice scopes --------------------------------------------
    session = svc.run_validate_scopes_stage(sid)
    assert session["stage"] == "scopes_validated"

    # -- stage 4: start capture ----------------------------------------------------
    session = svc.run_start_capture_stage(sid)
    assert session["stage"] == "capturing"

    # -- stage 5: accept the real WAV audio chunk (proves "audio accepted") --------
    session = svc.run_accept_audio_chunk_stage(sid, sequence=0, audio_bytes=wav_bytes)
    assert session["status"] == "active"
    assert session["total_chunks"] == 1
    assert session["total_audio_bytes"] == len(wav_bytes)

    # -- stages 6-11: assemble, STT, route, receive, TTS, metadata -----------------
    result = svc.finish_voice_session(sid)
    assert result["stage"] == "response_ready"
    assert result["status"] == "active"

    payload = svc.session_response_payload(sid)

    # "transcript produced by MockSpeechBackend"
    assert payload["transcript"], "MockSpeechBackend must have produced a non-empty transcript"
    with svc.repository.transaction() as connection:
        session_row = svc.repository.get_session(connection, sid)
    assert session_row["stt_backend"] == "mock"

    # "response generated through PublicChatRoutingService"
    assert payload["reply"], "PublicChatRoutingService.handle_message() must have produced a reply"

    # "TTS file generated by MockTtsBackend"
    assert payload["tts_audio_relative_path"]
    assert session_row["tts_backend"] == "mock"
    from core_model.mini_brain.voice_runtime import audio_session_manager

    tts_bytes = audio_session_manager.read_output(settings.resolved_voice_audio_dir, sid)
    assert tts_bytes, "the TTS output file must actually exist on disk with real bytes before close"
    assert tts_bytes.startswith(b"MOCKWAVE"), "TTS output must have been produced by mock_tts_backend"

    # -- stage 12: close / archive the session --------------------------------------
    closed = svc.close_voice_session(sid)
    assert closed["stage"] == "closed"
    assert closed["status"] == "completed", "session archived"

    # after close, the on-disk audio directory (chunks + assembled + tts output)
    # must be fully deleted -- ephemeral by default.
    assert audio_session_manager.session_dir_exists(settings.resolved_voice_audio_dir, sid) is False

    # -- "no raw audio stored in the database" --------------------------------------
    conn = sqlite3.connect(settings.resolved_database_path)
    voice_message_columns = [row[1] for row in conn.execute("PRAGMA table_info(mini_brain_voice_messages)").fetchall()]
    assert "audio_bytes" not in voice_message_columns
    assert "raw_audio" not in voice_message_columns
    assert "audio_blob" not in voice_message_columns

    rows = conn.execute(
        "SELECT message_type, sanitized_text, audio_hash FROM mini_brain_voice_messages WHERE session_id = ?",
        (session_row["id"],),
    ).fetchall()
    assert len(rows) == 3  # transcript, reply, tts_output
    for message_type, sanitized_text, audio_hash in rows:
        # the raw WAV bytes (or any substring of them long enough to be
        # meaningful) must never appear inside a persisted text column
        assert wav_bytes[:20] not in sanitized_text.encode("utf-8", errors="ignore")
        if message_type in ("transcript", "tts_output"):
            assert audio_hash is not None and len(audio_hash) == 64  # sha256 hex digest, not raw bytes

    # -- "MB-24 plugin state unchanged" ----------------------------------------------
    plugin_tables = [
        row[0] for row in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'mini_brain_plugin%'"
        ).fetchall()
    ]
    for table in plugin_tables:
        count = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        assert count == 0, f"{table} must remain empty -- a voice session must never touch MB-24's own tables"
    conn.close()


def test_denied_public_session_never_reaches_stt_or_tts(settings: Settings) -> None:
    """A session denied at the permission stage (no consent given) must
    never produce a transcript or TTS output -- confirms the smoke
    test's happy path is exercising real gating, not a stub that always
    succeeds."""
    svc = MiniBrainVoiceRuntimeService(settings)
    session = svc.create_voice_session(session_mode="public_chat", raw_client_key="192.0.2.101")
    sid = session["public_id"]
    session = svc.run_check_microphone_permission_stage(sid, explicit_consent_given=False)
    assert session["status"] == "denied"

    payload = svc.session_response_payload(sid)
    assert payload["transcript"] is None
    assert payload["reply"] is None
    assert payload["tts_audio_relative_path"] is None

    closed = svc.close_voice_session(sid)
    assert closed["status"] == "denied"
