"""MB-04B: Consistency Validator -- does the response actually line up
with the Response Plan that authorized it?

Deliberately does NOT duplicate MB-04A's `response_validator.py`
checks (language match, self-claimed-action phrases, overconfidence)
-- those already exist and still run as part of MB-04A's own pipeline.
This module checks different things MB-04A's validator does not:

1. confidence_without_backing_knowledge -- the Response Plan itself
   claiming high/medium confidence with zero Primary knowledge behind
   it (an internal Response Plan consistency check, not a text check)
2. response_not_grounded_in_provided_knowledge -- does the response
   share any real overlap with the knowledge/context the Response Plan
   actually supplied
3. forbidden_claim -- a fresh, MB-04B-owned list of self-claimed
   restricted-action phrases. Following this codebase's own
   established pattern (each phase reimplements a shared safety
   concept locally rather than importing another phase's private
   internals -- see MB-03's Rule Engine and MB-04A's own response
   validator, both independently encoding the same training-boundary
   rule), this is a deliberate, disclosed choice, not an oversight.
4. disclaimers_not_preserved -- structural check that the final
   response OBJECT still carries the exact disclaimers the Response
   Plan specified (disclaimers are attached by MB-04's own
   `format_response()`, never generated by the model itself)
"""

from __future__ import annotations

from typing import Any

_FORBIDDEN_CLAIM_PHRASES = (
    "i have started training", "i started training", "training has begun",
    "i will start the training", "i am executing", "i have executed",
    "i have deleted", "i have modified the dataset", "i granted access",
    "i have granted", "training is now running", "i have begun training",
    "i've started training", "i've executed", "i have updated the database",
    "i have changed the settings", "access has been granted",
)

MIN_GROUNDING_WORD_LENGTH = 5


def validate_consistency(
    *, response_text: str, response_plan: dict[str, Any], final_response: dict[str, Any] | None = None,
) -> dict[str, Any]:
    response_text = response_text or ""
    issues: list[str] = []

    knowledge = response_plan.get("validated_knowledge", {}) or {}
    primary = knowledge.get("primary", []) or []
    supporting = knowledge.get("supporting", []) or []
    matched_items = (response_plan.get("validated_context", {}) or {}).get("matched_items", []) or []

    confidence_band = response_plan.get("confidence_band")
    if confidence_band in ("high", "medium") and not primary:
        issues.append("confidence_without_backing_knowledge")

    known_terms = set(primary) | set(supporting) | set(matched_items)
    if known_terms:
        lowered_response = response_text.lower()
        grounded = any(
            word.lower() in lowered_response
            for term in known_terms
            for word in term.split()
            if len(word) >= MIN_GROUNDING_WORD_LENGTH
        )
        if not grounded:
            issues.append("response_not_grounded_in_provided_knowledge")

    lowered = response_text.lower()
    forbidden_hits = [phrase for phrase in _FORBIDDEN_CLAIM_PHRASES if phrase in lowered]
    if forbidden_hits:
        issues.append(f"forbidden_claim: {forbidden_hits}")

    if final_response is not None:
        expected_disclaimers = response_plan.get("disclaimers", [])
        actual_disclaimers = final_response.get("disclaimers", [])
        if expected_disclaimers != actual_disclaimers:
            issues.append("disclaimers_not_preserved")

    return {"passed": len(issues) == 0, "issues": issues}
